import { GoogleGenAI, type Content, type Part } from "@google/genai";
import {
  INFOGRAPHIC_STYLES,
  INFOGRAPHIC_LANGUAGES,
  type InfographicStyle,
  type InfographicLanguage,
} from "./infographicStyles";

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  throw new Error("GEMINI_API_KEY is not set in environment");
}

export const ai = new GoogleGenAI({ apiKey });

export const IMAGE_MODEL = "gemini-3-pro-image-preview";
export const INFOGRAPHIC_MODEL = "gemini-3-pro-image-preview";

export type Turn = {
  role: "user" | "model";
  text?: string;
  imageBase64?: string;
  imageMimeType?: string;
};

export type EditResult = {
  imageBase64: string;
  mimeType: string;
  text?: string;
};

export type InlineImage = {
  base64: string;
  mimeType: string;
};

export type InfographicAspect = "1:1" | "3:4" | "4:3" | "9:16" | "16:9";

export {
  INFOGRAPHIC_STYLES,
  INFOGRAPHIC_LANGUAGES,
  type InfographicStyle,
  type InfographicLanguage,
};

export type InfographicInput = {
  images: InlineImage[];
  description?: string;
  aspectRatio?: InfographicAspect;
  style?: InfographicStyle;
  language?: InfographicLanguage;
};

function turnToContent(turn: Turn): Content {
  const parts: Part[] = [];
  if (turn.imageBase64) {
    parts.push({
      inlineData: {
        mimeType: turn.imageMimeType ?? "image/png",
        data: turn.imageBase64,
      },
    });
  }
  if (turn.text) parts.push({ text: turn.text });
  return { role: turn.role, parts };
}

function extractImage(
  response: Awaited<ReturnType<typeof ai.models.generateContent>>,
): EditResult {
  const parts = response.candidates?.[0]?.content?.parts ?? [];
  let imageBase64: string | undefined;
  let mimeType = "image/png";
  let text: string | undefined;

  for (const part of parts) {
    if (part.inlineData?.data) {
      imageBase64 = part.inlineData.data;
      if (part.inlineData.mimeType) mimeType = part.inlineData.mimeType;
    } else if (part.text) {
      text = (text ? text + "\n" : "") + part.text;
    }
  }

  if (!imageBase64) {
    throw new Error(
      text
        ? `Gemini returned no image. Message: ${text}`
        : "Gemini returned no image (likely blocked by safety filters).",
    );
  }

  return { imageBase64, mimeType, text };
}

export async function editImage(turns: Turn[]): Promise<EditResult> {
  const contents = turns.map(turnToContent);

  const response = await ai.models.generateContent({
    model: IMAGE_MODEL,
    contents,
  });

  return extractImage(response);
}

const LANGUAGE_RULE: Record<InfographicLanguage, string> = {
  en: "Write ALL on-image text (titles, headlines, labels, captions, taglines, units) in English. Use natural, native English marketing phrasing. Do not mix languages. Numbers and universal symbols are fine.",
  ru: "Write ALL on-image text (titles, headlines, labels, captions, taglines, units) in Russian (Русский язык). Use natural, native Russian marketing phrasing — not transliteration. Do not mix languages. Numbers and universal symbols are fine.",
  uz: "Write ALL on-image text (titles, headlines, labels, captions, taglines, units) in Uzbek, written in the modern Latin alphabet (O'zbek tili, lotin alifbosi). Use natural, native Uzbek marketing phrasing — not transliteration of English or Russian. Do not mix languages. Numbers and universal symbols are fine.",
};

const COMPOSITING_DIRECTIVE = [
  "OPERATING MODE — this is an IMAGE EDIT, not an image generation:",
  "You are EDITING the attached reference photo, not generating a new product",
  "from scratch. Take the attached product photo as the source for what the",
  "PRODUCT IS — its identity, materials, prints, graphics, hardware, color,",
  "and silhouette. Reproduce all of those product details bit-identically.",
  "",
  "The PRODUCT is frozen. The PHOTOGRAPH is not.",
  "",
  "Specifically, you MUST preserve from the reference (the product layer):",
  "- Every printed word, logo, label, and slogan on the product surface.",
  "- Every graphic illustration, embroidered character, applique, or 3D",
  "  decorative element — exact line weight, pose, color, position.",
  "- Every pattern, print, weave, grain, and surface texture.",
  "- The product's color, shape, silhouette, proportions, and material.",
  "- Every real feature: buttons, zippers, seams, hems, hardware, joints,",
  "  bolts, mounts, clasps, trim — same count, same shape, same place.",
  "",
  "But you MUST DISCARD from the reference (the photograph layer):",
  "- The original background entirely — concrete floors, walls, doors,",
  "  rooms, outdoor surfaces, bystanders, the photographer's hand or foot,",
  "  any environmental context. None of it appears in the output.",
  "- The original lighting DIRECTION (which side of the product was lit,",
  "  where shadows fell) and any harsh raw-flash artifacts. You may relight",
  "  the product to match the new scene's key-light direction and intensity.",
  "  HOWEVER: the product's HUE and SATURATION stay identical to the",
  "  reference — re-lighting changes brightness and shadow placement, NOT",
  "  color. Do NOT 'correct white balance', 'neutralize color cast', or",
  "  'adjust' the product's color in any way.",
  "- The original camera angle if it is awkward or off-axis. Re-pose the",
  "  product to a clean three-quarter or straight-on hero angle that suits",
  "  the new layout.",
  "",
  "Mental model: this is a Photoshop composite with three layers:",
  "  1. PRODUCT layer — same physical product, RE-PHOTOGRAPHED in a studio.",
  "     Identity preserved bit-identically; lighting and angle re-shot.",
  "  2. SCENE layer — the styled background you compose around it.",
  "  3. TEXT layer — the typography and callouts.",
  "Layer 1's IDENTITY is frozen. Its photography is not. Layers 2 and 3",
  "are yours to author.",
  "",
  "If the reference photo shows the product against a messy real-world",
  "background (concrete, dirt, clutter, a person's foot, a kitchen counter,",
  "a packing box), you MUST replace that background entirely with the styled",
  "scene this prompt calls for. NEVER paste the original photo as-is into",
  "the layout — that is a failure mode, not the goal. The goal is to make",
  "it look as if a professional photographer re-shot the same product in a",
  "proper studio ten minutes after the reference was taken.",
  "",
  "If at any point you feel the urge to 'clean up', 'simplify', 're-balance',",
  "or 're-render' anything ON the product surface itself — buttons, prints,",
  "labels, hardware — you are working on the wrong layer. Stop and switch",
  "to Layers 2 or 3, or to re-lighting the product within Layer 1.",
  "",
].join("\n");

const ENHANCEMENT_BLOCK = [
  "PHOTOGRAPHIC ENHANCEMENT — re-photograph the product, never re-design it:",
  "The reference photo may be low quality: phone snapshot, dim or color-cast",
  "lighting, motion blur, soft focus, cluttered background, wrinkled fabric,",
  "dust, lint, smudges, glare, fingerprints, harsh shadows, awkward angle.",
  "Treat the reference as the SOURCE OF TRUTH for what the product IS, but",
  "as a STARTING POINT for how the product is photographed. Render the",
  "product in the output as if it were freshly captured by a professional",
  "product photographer in a high-end studio:",
  "- Tack-sharp pixel-level focus and high resolution across the entire",
  "  product surface.",
  "- Even, flattering studio-quality lighting that matches the scene's key-",
  "  light direction. Clean specular highlights with shape, soft fill,",
  "  controlled rim light, no harsh raw flash.",
  "- Lighting only — relight the product to match the new scene's key-",
  "  light direction and intensity. The product may appear brighter or",
  "  darker overall, but its HUE and SATURATION stay identical to the",
  "  reference. Do NOT 'correct', 'neutralize', 'adjust', 'rebalance', or",
  "  'restore' the product's color in any way. If the reference shows the",
  "  product as a specific shade — including any warmth, coolness, or",
  "  tint from the original photo's environment — the output shows that",
  "  EXACT same shade. You are not the white-balance authority on this",
  "  product. Whatever color the reference shows IS the product's color.",
  "- Surface cleanup — remove ONLY these specific photographic artifacts",
  "  that are clearly not part of the product: free-floating hair on the",
  "  fabric, visible dust specks in the air or on the lens, obvious",
  "  fingerprint smudges on glass/screens, motion blur. That is the",
  "  ENTIRE allowed cleanup list. You may NOT remove, smooth, simplify,",
  "  or 'clean up' anything else, including: wrinkles in fabric, creases,",
  "  texture variation, color variation, surface irregularities,",
  "  imperfect stitching, slight asymmetry, joint discoloration, scuffs",
  "  on hardware, or any feature you cannot positively identify as a",
  "  photographic artifact. When in doubt, preserve. A wrinkle you leave",
  "  alone is recoverable; a feature you 'cleaned up' is gone.",
  "- Keep ALL real product details: every button, zipper, seam, stitch,",
  "  label, tag, hardware element, joint, screw, bolt, mount, panel,",
  "  color block, material patch, and decorative element appears in the",
  "  output at the SAME position, shape, color, count, and proportion as",
  "  in the reference. Count buttons in the reference; the output has the",
  "  same count. Count zippers; same count. Count joints, screws, panels;",
  "  same count. The model must NOT consolidate, simplify, or 'tidy' the",
  "  product's feature inventory.",
  "- Replace the reference's cluttered or messy background entirely with the",
  "  styled scene this prompt calls for.",
  "- Straighten the product's pose if it is awkwardly tilted; flatten a",
  "  garment if it is bunched up; un-fold a corner if it obscures a graphic.",
  "",
  "Enhancement is NEVER a license to alter what the product IS. Do NOT use",
  "this clause as cover for redrawing, simplifying, restyling, recoloring,",
  "or substituting:",
  "- Printed text, character graphics, embroidered designs, pattern motifs,",
  "  surface prints, brand marks — preserve them exactly as in the reference.",
  "- The product's exact reference color, shape, silhouette, proportions, or material.",
  "- Any real, intentional product feature (zipper, button, seam, label,",
  "  trim, hardware, branded element).",
  "",
  "TWO-PHOTOGRAPHERS METAPHOR — the rule that resolves all ambiguity:",
  "Picture the reference photo as taken by an amateur with a phone in poor",
  "lighting. Picture the output as the SAME PRODUCT photographed by a",
  "professional ten minutes later in a proper studio. Between those two",
  "photographs, NOTHING about the product has been touched. The buttons are",
  "in the same places. The cut and silhouette of the garment are identical.",
  "The print on the chest is the SAME print, with the SAME line weight, the",
  "SAME color, the SAME character design in the SAME pose. The label says",
  "the SAME words. The fabric is the SAME fabric, the same weave, the same",
  "color. The pockets, seams, hems, zippers, hardware are in the same",
  "places, same count, same shape. Only the photography changed.",
  "",
  "If you find yourself wanting to make the product 'cleaner', 'more",
  "balanced', 'more elegant', 'more readable', or 'better designed' — STOP.",
  "That instinct is wrong. The product is already finished. Your job is the",
  "PHOTO, not the product.",
  "",
  "IDENTITY CHECK — perform this before finalizing the output:",
  "Mentally place the rendered product next to the reference photo. The two",
  "must be recognizable as the SAME PHYSICAL ITEM — the same SKU pulled off",
  "the same shelf. Run through this checklist:",
  "  1. Same silhouette and proportions? (cut, fit, length, width)",
  "  2. Same color, hue, and saturation as in the reference? No 'true",
  "     color' inference, no white-balance correction, no tint shift.",
  "     The product's color in the output matches the reference exactly,",
  "     even if the reference's color was affected by the original photo's",
  "     lighting. Whatever color you saw in the reference IS the answer.",
  "  3. Same printed graphics in the same positions? (line weight, character",
  "     design, pose, palette unchanged)",
  "  4. Same material and texture? (cotton stays cotton, denim stays denim,",
  "     plastic stays plastic, with the same weave/grain visible)",
  "  5. Same real features in the same places? (every button, zipper, label,",
  "     seam, hem, pocket, strap, hardware element)",
  "If ANY answer is no, you have redesigned the product. Restore the",
  "reference's identity and re-render.",
  "",
].join("\n");

const FIDELITY_BLOCK = [
  "ABSOLUTE PRODUCT FIDELITY — read first, applies above all other instructions:",
  "The attached reference photo(s) show the EXACT product. Treat it as a fixed,",
  "immutable asset that must appear in the output IDENTICAL to the reference.",
  "You may relight, reposition, rotate, scale, or replace its background. You",
  "may NOT, under ANY circumstance, alter:",
  "- Printed text on the product (logos, slogans, labels) — every word must",
  "  match character-for-character. If the t-shirt says 'MY FRIEND', the",
  "  output t-shirt must say 'MY FRIEND', not nothing and not something else.",
  "- Patterns, prints, or surface designs (sprinkles, stripes, dots, florals,",
  "  camo, plaid). Preserve density, color, scale, and placement exactly.",
  "- Embroidered, applique, fluffy, or 3D decorative elements — preserve their",
  "  exact shape, texture, character design, pose, and position.",
  "- Printed graphics or character illustrations on the product. Do NOT",
  "  redraw, simplify, restyle, or substitute with a generic version. Match",
  "  the original character's pose, expression, color, and rendering style.",
  "- The product's color, shape, silhouette, proportions, or material.",
  "- Any care labels, brand marks, tags, stitching, or trim.",
  "",
  "If you cannot reproduce a printed graphic faithfully, leave it blank rather",
  "than inventing a different one. A missing detail is recoverable; a wrong",
  "detail is a failure. The product in the output MUST be recognizable as the",
  "SAME PHYSICAL ITEM as the reference photo, not a 'similar' product.",
  "",
  "- FULL PRODUCT VISIBILITY — non-negotiable: every decorative element on",
  "  the product (printed text, embroidered characters, pattern motifs,",
  "  graphic prints, brand marks) must be plainly visible at full size. Do",
  "  not hide any portion of a graphic by folding, cropping, stacking,",
  "  perspective angle, or scene props. If the reference photo shows the",
  "  product flat-laid, the output is flat-laid. If on a hanger, on a hanger.",
  "  If on a model, on a model. Match the reference's presentation mode.",
  "",
].join("\n");

function buildInfographicPrompt(
  description: string | undefined,
  style: InfographicStyle,
  language: InfographicLanguage,
): string {
  const trimmed = description?.trim() ?? "";
  const languageRule = LANGUAGE_RULE[language];
  const hasDescription = trimmed.length > 0;

  const copyDirective = hasDescription
    ? [
        "COPY SOURCE — where every word on the image must come from:",
        "A product description has been provided at the bottom of this prompt.",
        "Treat that description as the SINGLE SOURCE OF TRUTH for every word",
        "rendered on the image — the product name, headline, feature labels,",
        "callout captions, taglines, technical specs, benefit titles, CTA",
        "wording, all of it. Extract the relevant phrases from the description",
        "and place them in the slots this style calls for. Do not paste the",
        "description verbatim — distill it into short, well-crafted on-image",
        "copy. Do not invent product names, features, claims, certifications,",
        "or numbers that cannot be derived from the description.",
        "",
        "ABSOLUTE RULE — illustrative phrases are NEVER rendered:",
        "Anywhere in this prompt where a sample phrase appears inside single",
        "or double quotes within an 'e.g.', 'such as', or parenthetical",
        "example — for instance 'Model 2025', 'Product', 'Care', 'Size Chart',",
        "'Unisex ⌄', 'Premium ⌄', 'JUST DO IT.', 'Move Forward.', 'Other",
        "Colors →', 'See More →', 'PURE', 'QUIET LUXURY', 'Sneakers',",
        "'Headphones', 'Bottle', 'TWISTRUSS', 'AHAR PLUS', 'ProControl',",
        "'Wide Size Range', '35–42', '128 GB', '500 ml', 'model @2025',",
        "'100% Cotton', 'Long Lasting', 'Matte Finish' — those words are",
        "EXAMPLES OF FORMAT ONLY and must NEVER appear on the image. Replace",
        "every one of them with wording you derive from the actual product",
        "description for this generation.",
      ].join("\n")
    : [
        "COPY SOURCE — where every word on the image must come from:",
        "No product description was provided. Read the product carefully from",
        "the reference photos — identify its category, materials, visible",
        "features, brand name (only if clearly printed), and the most likely",
        "3–5 selling points. Then write all on-image copy yourself in",
        "confident, benefit-led marketing phrasing. Do not invent specific",
        "numbers, certifications, or factual claims you cannot verify from",
        "the photos themselves.",
        "",
        "ABSOLUTE RULE — illustrative phrases are NEVER rendered:",
        "Anywhere in this prompt where a sample phrase appears inside single",
        "or double quotes within an 'e.g.', 'such as', or parenthetical",
        "example — for instance 'Model 2025', 'Product', 'Care', 'Size Chart',",
        "'JUST DO IT.', 'PURE', 'QUIET LUXURY', 'Sneakers', 'TWISTRUSS',",
        "'Wide Size Range', '128 GB' — those words are EXAMPLES OF FORMAT",
        "ONLY and must NEVER appear on the image. Replace every one of them",
        "with wording you author for this specific product.",
      ].join("\n");

  if (style === "cards") {
    return [
      FIDELITY_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE marketplace infographic in the",
      "style used on Wildberries / Ozon premium product listings: a 2×2 grid of",
      "four separate rounded-corner panels on a light neutral background, sharing",
      "a single cohesive color story derived from the product itself.",
      "",
      "SINGLE-VIEW RULE — read this first, it overrides everything below:",
      "Re-photograph the product ONCE — a clean, well-lit hero view in a studio",
      "(three-quarter angle, straight-on, or whatever best shows the product's",
      "structure). That ONE re-photographed view is the source for ALL FOUR",
      "PANELS. Every other panel either:",
      "  (a) shows the SAME hero view at different scale/framing/lighting/crop,",
      "      or",
      "  (b) shows a tight ZOOM CROP into a specific region of that hero view.",
      "You MAY NOT invent additional viewing angles — no rotated views, no",
      "imagined back/side/interior shots, no second photoshoot. If multiple",
      "reference photos are provided, you may use them as additional source",
      "views; if only one reference is provided, every panel derives from your",
      "single re-photographed hero. The product's identity (proportions,",
      "joints, hardware, every structural element) must be IDENTICAL across",
      "every panel because every panel is the same physical item.",
      "",
      "Panel layout:",
      "- Top-left (HERO): the re-photographed hero view at full size, with the",
      "  product's name as oversized soft-tone display typography behind/around",
      "  it. One small floating chip with a key fact derived from the description.",
      "  Light background.",
      "- Top-right (SPECS / FEATURES): 4 small sub-tiles inside this panel,",
      "  each a TIGHT ZOOM CROP into a different region of the SAME hero view —",
      "  a corner joint, a foot detail, the rail texture, the hinge mechanism.",
      "  These are crops of the hero, not new photos. Do NOT invent macro",
      "  detail that isn't visible in the hero. Mix of dark-background and",
      "  light-background sub-tiles for visual variety.",
      "- Bottom-left (MODES / USE CASES): a darker, moodier rendering of the",
      "  SAME hero view (re-lit with dramatic studio lighting, dark background)",
      "  showing the product in lifestyle context (e.g. with clothes hanging",
      "  on it, in a dim room). The product's silhouette, joints, hardware,",
      "  and proportions match the hero exactly. Two short labels with one-",
      "  line captions placed in negative space.",
      "- Bottom-right (BENEFITS): the SAME hero view at a different framing",
      "  or zoom (NOT a new angle), on a light panel. 3 stacked benefit blocks",
      "  (bold short title + 2–3 line caption) authored from the description.",
      "",
      "IDENTITY ACROSS PANELS — non-negotiable:",
      "Every panel shows the same physical product. Count: same number of rails,",
      "bars, joints, feet, screws, hinges, panels, buttons, seams. Materials:",
      "same metal finish, same plastic color, same wood grain. Hardware: same",
      "joint mechanism (if input has a metal disc with bolts, output has a",
      "metal disc with bolts — never substitute a different joint type). If",
      "you find yourself drifting toward a 'generic version' of this product",
      "category — STOP. The output must be the user's specific item, not a",
      "stock photo of a similar item.",
      "",
      "Typography: bold sans-serif. Strong size hierarchy — huge, medium, small.",
      "Headline weight heavy; body weight regular. Labels are short (1–3 words).",
      "",
      "Strict no's: no circular icon badges with thin-line icons, no arrow",
      "callouts pointing at a centered product, no rainbow color accents, no",
      "stock-template feel.",
      "",
      "PANEL BOUNDARY ENFORCEMENT — read this rule first, it is the single",
      "most important constraint on this layout:",
      "",
      "The four rounded panels are HARD WINDOWS. Every pixel of every product",
      "image MUST be contained INSIDE one of the four panels. Nothing of the",
      "product — no rod, no bar, no leg, no edge, no shadow of the product",
      "itself, no fragment of the reference photo, no portion of its original",
      "environment — may exist on the canvas OUTSIDE the panel borders.",
      "",
      "Mental model: the four panels are physical photographs lying on a sheet",
      "of plain paper. The paper underneath them is empty solid color. If you",
      "lifted any panel off the paper, the area beneath would be blank — not a",
      "copy of the product, not the original photo, not a backdrop layer, not",
      "anything. The panels are the ONLY place the product appears.",
      "",
      "Specifically forbidden — these break the layout:",
      "- The reference photo rendered at ANY opacity (full, faint, ghosted, or",
      "  in between) anywhere on the canvas behind the panels.",
      "- Any portion of the product extending past a panel border — a rod",
      "  poking out, a bar bridging two panels, an edge crossing the seam,",
      "  a leg stretching into the gap.",
      "- The original photograph's environment (concrete, walls, floor,",
      "  weeds, dirt, the photographer's foot, any outdoor/indoor backdrop)",
      "  visible anywhere in the gap zones.",
      "- A 'connecting' visual element of any kind in the gaps between panels.",
      "- Atmospheric haze, blur, gradient, or texture in the gap zones.",
      "- Treating the canvas as a full-bleed product backdrop with the four",
      "  panels as windows or cutouts on top.",
      "",
      "If you find yourself rendering the product as a full-canvas image and",
      "placing the panels on top, STOP. That is the failure mode. The product",
      "is INSIDE each panel as a separate composition — never across panel",
      "borders, never behind them, never around them.",
      "",
      "FINAL VISUAL CHECK — perform this before committing pixels:",
      "Look at the canvas. Identify the four rounded-rectangle panels. Look",
      "at every region OUTSIDE those four shapes — the horizontal gap between",
      "top and bottom rows, the vertical gap between left and right columns,",
      "the canvas margins around all four edges. Every one of those gap zones",
      "must be SOLID NEUTRAL COLOR with NOTHING visible in it except the",
      "shadows cast by the panels themselves. If you see any product imagery,",
      "reference-photo content, or environmental texture in any gap zone, the",
      "layout has failed. Restart.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image containing the four panels.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING:",
      "Place the rendered hero panel mentally next to the reference photo.",
      "Same number of structural elements? Same joint type? Same proportions?",
      "Same materials? Same color, hue, and saturation (no white-balance",
      "correction, no tint shift)? If any answer is no, you've drifted into",
      "a generic version. Restore the reference's identity, then propagate",
      "that single view across all four panels.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  if (style === "ticket") {
    return [
      FIDELITY_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE split-canvas ticket-stub editorial composition.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print,",
      "graphic, embroidery, color, button, seam stays exactly as in the source).",
      "But the LAYOUT around the product is required to be aggressive and graphic.",
      "You ARE permitted (and required) to do all of the following — these are",
      "SCENE / COMPOSITION operations, not product modifications:",
      "- Build a vertical split background (~60% black on the left, ~40%",
      "  saturated accent color on the right) underneath the product.",
      "- Tilt the product 10–25° from horizontal within the frame (rotation,",
      "  not redraw).",
      "- Position the product so it visually OVERLAPS the seam between the",
      "  two regions and bridges them (placement, not redraw — the seam runs",
      "  behind the product).",
      "- Add the ticket-stub graphics on the right region: barcodes, dotted",
      "  perforation line, decorative low-opacity letterform, etc.",
      "- Add a top nav strip, massive display headline, sub-headline,",
      "  feature list, tagline, body paragraph, and CTA pill in the dark",
      "  region — all overlaid in the SCENE / TEXT layers around the product.",
      "Do all of this. The product appears unchanged; the layout around it is",
      "fully designed.",
      "",
      "STYLE — TICKET STUB EDITORIAL (split-canvas fashion-catalog spread with ticket-design right side):",
      "",
      "COLOR LOCK — zero decision freedom, follow exactly:",
      "  Step 1: Identify the product's dominant color in the reference",
      "    photo (one word — red, blue, green, yellow, orange, pink,",
      "    purple, brown, black, white, gray). If the product is multi-",
      "    colored, pick the color that occupies the largest surface area.",
      "  Step 2: Render the product in the output with EXACTLY that color,",
      "    bit-identical to the reference (same hue, same saturation, same",
      "    value — no shift). All other product colors stay as in the",
      "    reference.",
      "  Step 3: The accent color used for the right-region background MUST",
      "    EQUAL the product's dominant color from Step 1. Same hue, same",
      "    saturation. A red product → red right-region. A blue product →",
      "    blue right-region. No substitution, no contrast, no complementary",
      "    color, no harmonization decision.",
      "  Step 4: Edge case — if the product's dominant color is black,",
      "    white, or a near-neutral gray, the accent becomes a single rich",
      "    saturated hue you may pick (cobalt, emerald, crimson, amber,",
      "    etc.) — but the product itself still renders with its exact",
      "    reference color, never tinted to match the accent.",
      "There is no creative choice. The product's reference color dictates",
      "both the product's output color AND the accent color. If you find",
      "yourself wanting to recolor the product to balance the palette, STOP",
      "— the rule is broken. The accent already equals the product.",
      "",
      "- Background: a vertical asymmetric split — the LEFT ~60% of the canvas is",
      "  pure black or very dark charcoal, the RIGHT ~40% is the accent color",
      "  from the COLOR LOCK above (equal to the product's dominant color). The",
      "  two regions meet at a clean vertical edge running floor to ceiling.",
      "- Ticket stub — defining structural move: the right region is designed as",
      "  a TICKET STUB or ADMISSION CARD, with a real-looking barcode + digits",
      "  at the very top, a second smaller barcode at the bottom, a horizontal",
      "  dotted perforation line near the bottom suggesting it can be torn off,",
      "  and optionally a single MASSIVE letterform glyph (Cyrillic, Latin, or",
      "  whichever the description's language uses) at very low opacity inside",
      "  the ticket as decorative texture.",
      "- Product: photorealistic, dramatically sized, tilted at 10–25° from",
      "  horizontal, OVERLAPPING the seam between the two regions so it visually",
      "  bridges the dark and accent halves. Occupies ~55–70% of canvas height.",
      "  This overlap is the second defining move — the product anchors the",
      "  composition by belonging to both sides at once.",
      "- Top nav strip (across the dark region): a thin row of 3–4 short",
      "  categorical tab-like labels in a light sans-serif. Author the labels",
      "  yourself from product attributes mentioned in the description (or,",
      "  with no description, from the product category). Reads like a",
      "  magazine top nav or a product-page tab bar.",
      "- Display headline: a MASSIVE bold condensed sans-serif word in white",
      "  inside the dark region, all caps, set against the upper-left area —",
      "  the product category in one short word, tightly tracked. Optional",
      "  small period or accent mark after the word for typographic detail.",
      "- Sub-headline: directly beneath, a smaller bold sans-serif label with",
      "  an optional small disclosure caret (e.g. 'Unisex ⌄', 'Premium ⌄').",
      "- Feature list: 2–4 short feature callouts in the dark region beneath",
      "  the sub-headline, each prefixed with a small '⊕' glyph, followed by a",
      "  bold short label and a one-line caption in a lighter weight beneath.",
      "  These are NOT chips — just plain text with a leading plus glyph.",
      "- Tagline + body: at the bottom of the dark region, a short bold tagline",
      "  in white ('JUST DO IT.', 'Move Forward.', or equivalent in the",
      "  description's language) plus a 3–5 line body paragraph in small light-",
      "  weight sans-serif beneath it.",
      "- Inside the ticket: a bold sans-serif model or variant name near the",
      "  top, a small label beneath, then a pill-shaped button in the dark",
      "  color with white text (status or short tagline). Lower in the ticket:",
      "  a key spec callout in oversized bold sans (size range, capacity,",
      "  count) followed by a black pill-shaped CTA button with a right-arrow",
      "  ('Other Colors →', 'See More →', etc.).",
      "- Color: high-contrast pairing — pure black + the LOCKED accent",
      "  (equal to the product's dominant color per the COLOR LOCK) +",
      "  white. The product's own natural colors come through unchanged —",
      "  same red is the same red, same blue is the same blue. The accent",
      "  equals the product; do not touch either. No third accent color,",
      "  no rainbow palette.",
      "- Typography: ONE bold condensed display sans for the massive headline,",
      "  ONE clean modern sans for everything else. No serif, no script, no",
      "  decorative typography.",
      "- Avoid: gradients, atmospheric haze, vignettes, glassy '+' pill chips,",
      "  circular icon badges, decorative botanical props, soft pastel washes,",
      "  oversized backdrop words behind the product, single-color backgrounds",
      "  without the split. This style is graphic, structured, and reads as a",
      "  fashion-catalog spread.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The split-canvas ticket-stub composition is YOUR creative work. The",
      "product itself is NOT. Apply the two-photographers metaphor: the product",
      "in the output is the SAME PHYSICAL ITEM as the reference, photographed",
      "by a professional in better conditions. The black region, the accent",
      "color half, the barcodes, the perforation, the top nav, the headlines",
      "and tagline, the ticket text, and the CTA pill are yours to compose.",
      "The product's silhouette, color, material, every printed text, every",
      "graphic illustration, every embroidered character, every pattern,",
      "every button, seam, label, hem, and hardware element is FIXED — copied",
      "from the reference, never re-imagined. The split seam runs BEHIND the",
      "product, not THROUGH it; the product visually bridges the two halves",
      "but is rendered as a single complete unaltered item. Run the 5-point",
      "identity check from the ENHANCEMENT block one final time before",
      "committing pixels: silhouette, color, prints, material, features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  if (style === "flagship") {
    return [
      FIDELITY_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      // copyDirective,
      // "",
      "Edit the attached product photo into ONE premium e-commerce flagship listing.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print,",
      "graphic, embroidery, color, button, seam, hardware stays exactly as in the",
      "source). But the LAYOUT around the product is required to be aggressive and",
      "graphic. You ARE permitted (and required) to do all of the following — these",
      "are SCENE / COMPOSITION operations, not product modifications:",
      "- Build a vertical split background (~40% pure white on the left, ~60%",
      "  saturated accent color on the right) underneath the product.",
      "- Hero product treatment — defining move: re-photograph the product",
      "  large and dramatically cropped so it fills the colored region and",
      "  bleeds off the right and bottom edges. The crop is a framing decision",
      "  about which portion of the PRODUCT is shown — not which portion of",
      "  the original snapshot. Re-light, re-pose, and remove the original",
      "  background entirely. Whatever portion of the product is visible must",
      "  be rendered with the SAME prints, graphics, color, material, and",
      "  hardware as in the reference. Over-scaled for graphic impact, never",
      "  redesigned. Occupies ~70–85% of the colored region.",
      "- Add a vertical script / italic watermark of the model name running",
      "  up the right edge of the colored region at low opacity.",
      "- Add a top nav strip with brand logo + 3–4 tab labels + small line",
      "  icons.",
      "- Add a stacked headline block (category / model / positioning",
      "  statement) in the upper-left of the white region.",
      "- Add 2–3 vertical feature cards down the white region, each with a",
      "  pill-shaped tech-name tag, a 1–2 line caption, and a small thumbnail",
      "  cropped from the reference photo.",
      "- Add a bottom CTA pill in the accent color and a small footer.",
      "Do all of this. The product appears unchanged within whatever region of",
      "the reference is visible; the layout around it is fully designed.",
      "",
      "STYLE — FLAGSHIP LISTING (premium e-commerce product page, modern marketplace top-tier):",
      "",
      "COLOR LOCK — zero decision freedom, follow exactly:",
      "  Step 1: Identify the product's dominant color in the reference",
      "    photo (one word — red, blue, green, yellow, orange, pink,",
      "    purple, brown, black, white, gray). If the product is multi-",
      "    colored, pick the color that occupies the largest surface area.",
      "  Step 2: Render the product in the output with EXACTLY that color,",
      "    bit-identical to the reference (same hue, same saturation, same",
      "    value — no shift). All other product colors stay as in the",
      "    reference.",
      "  Step 3: The accent color used for the right-region background,",
      "    the CTA pill, and the tech tags MUST EQUAL the product's",
      "    dominant color from Step 1. Same hue, same saturation. A red",
      "    product → red right-region background. A blue product → blue",
      "    right-region. No substitution, no contrast, no complementary",
      "    color, no harmonization decision.",
      "  Step 4: Edge case — if the product's dominant color is black,",
      "    white, or a near-neutral gray, the accent becomes a single",
      "    rich saturated hue you may pick (cobalt, emerald, crimson,",
      "    amber, etc.) — but the product itself still renders with its",
      "    exact reference color, never tinted to match the accent.",
      "There is no creative choice. The product's reference color dictates",
      "both the product's output color AND the accent color. If you find",
      "yourself wanting to recolor the product to balance the palette, STOP",
      "— the rule is broken. The accent already equals the product.",
      "",
      "REGION BOUNDARY ENFORCEMENT — read this rule first, it is the single",
      "most important constraint on this layout:",
      "",
      "The product appears on this canvas in EXACTLY two places, and nowhere",
      "else:",
      "  1. The dramatically CROPPED HERO inside the colored region (right",
      "     ~60%), bleeding off the right and bottom edges by design.",
      "  2. The small THUMBNAILS inside the feature-card panels in the white",
      "     region.",
      "No third appearance. No fourth.",
      "",
      "Mental model: the canvas has TWO regions — a solid white left region",
      "and a solid accent-color right region. The colored region contains",
      "ONLY the cropped hero plus the vertical script watermark. The white",
      "region contains ONLY typography, feature-card panels (with their tiny",
      "thumbnails inside), and the CTA pill. Strip away the type and panels",
      "and you are left with two flat fields of color and nothing else.",
      "",
      "Specifically forbidden — these break the layout:",
      "- The reference photo rendered at ANY opacity (full, faint, ghosted,",
      "  or full-bleed) as a backdrop layer beneath the white region.",
      "- Any portion of the product visible in the white region OUTSIDE the",
      "  small feature-card thumbnails — no large faded silhouette behind",
      "  the headline block, no rod or bar extending from the colored region",
      "  into the white region, no product fragment floating in the white",
      "  region's empty space.",
      "- Product imagery sitting on the vertical seam between the two regions",
      "  or bleeding across that seam in either direction.",
      "- The original photograph's environment (concrete, walls, floor,",
      "  weeds, dirt, the photographer's foot, any outdoor or indoor",
      "  backdrop) visible anywhere on the canvas — not in the white region,",
      "  not in the colored region behind the hero, not inside the feature-",
      "  card thumbnails.",
      "- Treating the canvas as a full-bleed product backdrop with the white",
      "  region painted on top of it like a side panel, or treating the white",
      "  region as a window onto a hidden product layer beneath.",
      "",
      "The vertical SCRIPT WATERMARK of the model name in the colored region",
      "IS allowed and IS expected — that is decorative typography (letterforms",
      "only), not product imagery. It does NOT count as a forbidden second",
      "appearance of the product.",
      "",
      "If you find yourself rendering the product as a full-canvas image and",
      "painting the white region on top of it, STOP. That is the failure mode.",
      "The product appears ONLY in the hero crop and ONLY in the feature-card",
      "thumbnails — never as a backdrop, never bleeding past region borders,",
      "never in the white region's empty space, never on the seam.",
      "",
      "FINAL VISUAL CHECK — perform this before committing pixels:",
      "Look at the canvas. Identify the two regions (white left, accent-color",
      "right). In the WHITE region, the only product imagery is the small",
      "thumbnails inside the feature-card panels — every other pixel of the",
      "white region is solid white with typography or feature-card panels on",
      "top. In the COLORED region, the only product imagery is the single",
      "dramatic hero crop — every other pixel of the colored region is solid",
      "accent color with the script watermark on top. If you see product",
      "silhouettes, faded copies, environmental texture, or reference-photo",
      "content anywhere outside those two specific containers, the layout has",
      "failed. Restart.",
      "- Background: vertical asymmetric split — the LEFT ~40% of the canvas",
      "  is pure white, the RIGHT ~60% is the accent color from the COLOR",
      "  LOCK above (which equals the product's dominant color). The two",
      "  regions meet at a clean vertical edge running floor to ceiling.",
      "- Hero product treatment — defining move: a region of the actual",
      "  reference photo is blown up large to fill the colored region,",
      "  cropped to bleed off the right and bottom edges. Pick the most",
      "  visually striking region of the reference (one that contains a",
      "  printed graphic, branded detail, or signature material), then",
      "  enlarge THAT region pixel-faithfully — do not invent macro detail",
      "  the reference photo does not show. If a printed graphic,",
      "  embroidered element, or text falls inside the chosen region, it",
      "  appears in the output unchanged (same line weight, same color,",
      "  same character pose). Over-scaled for graphic impact, never",
      "  redesigned. Occupies ~70–85% of the colored region.",
      "- Vertical watermark: a repeating script or italic of the product /",
      "  model name (drawn from the description) runs vertically up the",
      "  right edge of the colored region at very low opacity in a slightly",
      "  darker shade of the accent color, decorative texture only. If no",
      "  product name is available, omit the watermark entirely.",
      "- Top nav strip (spans both regions): a thin row at the very top",
      "  with a small brand logo or wordmark on the far left, 3–4 short",
      "  tab-like labels immediately to its right authored from product",
      "  attributes in the description (or, with no description, from the",
      "  product category), and a pair of small line icons (heart + cart)",
      "  on the far right. Reads like a real e-commerce product-page",
      "  header.",
      "- Headline block (upper-left of the white region), in dark near-",
      "  black, with generous breathing room between tiers:",
      "    1. A bold sans CATEGORY word at the top (single word for the",
      "       product type, drawn from the description).",
      "    2. The full product / model NAME beneath in a slightly smaller",
      "       bold sans (drawn from the description).",
      "    3. A short one-line POSITIONING statement under that in a",
      "       light-weight sans.",
      "    4. Optional micro-row beneath: a small horizontal cluster of",
      "       3–5 colored circular dots (color-variant swatches in real",
      "       product colors) AND/OR a tiny five-star rating row in dark",
      "       gray. Include only if the description supports it; omit",
      "       otherwise.",
      "- Hairline rule: a 1px light-gray horizontal rule separates the",
      "  headline block from the feature cards beneath it.",
      "- Feature cards — second defining move: a vertical STACK of 2–3",
      "  cards down the white region. Each card is a small rounded-corner",
      "  light-gray panel with generous internal padding, containing: a",
      "  small pill-shaped tech / spec tag (1–2 words drawn from the",
      "  description) in a heavier weight, a short 1–2 line caption",
      "  beneath explaining the feature, and a small thumbnail in the",
      "  corner. The thumbnail is a tightly cropped detail of the SAME",
      "  reference photo (a region of the actual product), not an",
      "  imagined alternate angle. If multiple references are provided,",
      "  you may use different ones across the cards.",
      "- Bottom CTA: in the lower-left, a large rounded pill-shaped",
      "  button in the accent color (matching the right region) with",
      "  white text in two tiers — a small upper label naming a primary",
      "  spec dimension drawn from the description, and an oversized",
      "  bold value beneath showing the corresponding value (set in",
      "  tabular figures so digits align). The CTA itself shows a real",
      "  spec, not a fake price tag.",
      "- Footer: omit unless the description contains a specific",
      "  disclosure worth showing (year, edition, license, certification,",
      "  origin). If included, set in tiny faint-gray sans at the very",
      "  bottom of the white region.",
      "- Color: a strict three-tone palette — white (left region +",
      "  feature cards), the LOCKED accent (right region + CTA pill +",
      "  tech tags, equal to the product's dominant color per the COLOR",
      "  LOCK), and dark near-black (typography). The product's natural",
      "  colors come through unchanged in the hero crop and in every",
      "  feature-card thumbnail — same red is the same red, same blue",
      "  is the same blue. The accent equals the product; do not touch",
      "  either. No third accent.",
      "- Typography: ONE clean modern sans-serif family throughout",
      "  (Inter / SF Pro / Söhne feel), used at multiple sizes and",
      "  weights, with tight optical kerning at display size and",
      "  generous leading on body. Use tabular figures for every numeric",
      "  value (specs, ratings). No serif and no script except for the",
      "  vertical watermark.",
      "- Spacing: the white region carries more negative space than",
      "  information. The layout reads calm and refined, never crowded.",
      "- Avoid: gradients, atmospheric haze, vignettes, decorative",
      "  botanical props, full-uncropped product hero shots (the",
      "  dramatic crop is essential), color blocking beyond the white-",
      "  plus-one-accent split, '+' pill chips with captions, numbered",
      "  features (01/02/03), oversized backdrop typography, fake price",
      "  tags, fabricated star counts. This style is informational,",
      "  refined, and reads as a flagship product listing — not a brand",
      "  poster.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The flagship listing layout is YOUR creative work. The product itself",
      "is NOT. Apply the two-photographers metaphor: the product in the",
      "output is the SAME PHYSICAL ITEM as the reference, photographed by a",
      "professional in better conditions. The split background, the top nav",
      "strip, the vertical watermark, the headline tiers, the feature cards,",
      "the tech tags, the CTA pill, and the footer text are yours to compose.",
      "The product's silhouette, color, material, every printed text, every",
      "graphic illustration, every embroidered character, every pattern,",
      "every button, seam, label, hem, and hardware element is FIXED — copied",
      "from the reference, never re-imagined.",
      "",
      "CROPPING CONSTRAINT — read carefully:",
      "The dramatic crop frames PART of the product, but the part that IS",
      "shown must be rendered as the EXACT corresponding part of the actual",
      "reference product. The crop chooses WHICH region of the product is",
      "visible — it does NOT permit you to redesign whatever is inside that",
      "region. If a printed graphic or embroidered element falls inside the",
      "cropped region, it appears in the output unchanged: same line weight,",
      "same color, same character pose. If you cannot fit the printed area",
      "fully inside the crop without altering it, RECOMPOSE the crop to",
      "include the printed area in full rather than cutting through it.",
      "",
      "Run the 5-point identity check from the ENHANCEMENT block one final",
      "time before committing pixels: silhouette, color, prints, material,",
      "features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  // default: glass
  return [
    FIDELITY_BLOCK,
    COMPOSITING_DIRECTIVE,
    ENHANCEMENT_BLOCK,
    copyDirective,
    "",
    "STEP 1 — DECORATION AUDIT (do this BEFORE composing the scene):",
    "Look at every reference photo. List, in your head, every single printed",
    "word, every graphic illustration, every embroidered character, every",
    "pattern motif visible on the product. If the t-shirt says 'MY FRIEND'",
    "with a cartoon character, the t-shirt in the output MUST say 'MY FRIEND'",
    "with the SAME cartoon character in the SAME pose, color, and position.",
    "If the bottle label has specific text and a specific image, that exact",
    "text and that exact image MUST appear on the bottle in the output.",
    "These printed and embroidered elements are the HERO of the entire image.",
    "Build the glassmorphism scene AROUND them — never let the scene replace,",
    "simplify, restyle, or omit them. If you cannot reproduce a printed",
    "graphic exactly, leave that area blank rather than inventing a new one.",
    "",
    "STEP 2 — SCENE PROTECTS THE PRODUCT:",
    "Atmospheric haze, bloom, glass bubbles, glass shelves, frosted panels,",
    "and any other scene element must NEVER blur, soften, fade, occlude, or",
    "pass in front of the product itself or any printed/embroidered content",
    "on it. The product is photographically crisp from edge to edge, with",
    "every graphic clearly legible. The glass effects belong to the SCENE",
    "AROUND the product, not the product surface.",
    "",
    "Now edit the attached product photo into ONE editorial advertisement in",
    "glassmorphism style. The product itself stays unchanged; only the scene,",
    "atmosphere, glass staging elements, and typography are added around it.",
    "The ENTIRE composition must feel layered with glass — not just the callouts.",
    "",
    "Setting — choose CONTEXTUALLY based on the product, build either:",
    "(a) A bright interior suited to the product's lifestyle context, OR",
    "(b) A styled commercial scene with THEMED props on a complementary",
    "    backdrop that reinforces the product's identity:",
    "    - Sea / ocean / fresh → sand, seashells, coral, soft teal backdrop.",
    "    - Garden / floral / botanical → leaves, petals, soft green backdrop.",
    "    - Citrus / tropical → fruit slices, palm leaves, warm yellow backdrop.",
    "    - Winter / mint / cool → frost, eucalyptus, pale blue backdrop.",
    "    - Forest / woody / spice → bark, dried botanicals, warm brown backdrop.",
    "    - Beauty / skincare → soft drapery, marble, pearl tones.",
    "    - Apparel → sunlit bedroom, linen, pale wood floor.",
    "    - Tech → modern desk, pale concrete or oak.",
    "    - Kitchen / food → wooden table, marble counter, fresh ingredients.",
    "    - Bath / shower / plumbing → marble bathroom, pale tile, soft daylight.",
    "    - Toys / kids → pastel nursery, soft playful props.",
    "",
    "If no theme is obvious, choose a bright interior that fits. The setting",
    "must always be bright with atmospheric depth. Vary specific props per",
    "product so different products do NOT share the same backdrop.",
    "",
    "Glassmorphism scene staging — the COMPOSITION must feel glass-layered:",
    "- The product is staged WITH at least one large translucent or frosted",
    "  glass element in the scene, chosen to fit the product type:",
    "    • Tabletop / standing products (bottles, jars, gadgets) → a clear",
    "      glass shelf or pedestal beneath the product PLUS a tall translucent",
    "      glass panel positioned behind it as a vertical backdrop layer.",
    "    • Wall-mounted products (shower, faucets, sconces) → a tall frosted",
    "      glass shower screen, glass partition, or translucent glass panel",
    "      visible alongside the product as an architectural element.",
    "   • Apparel / textile → present the garment FULLY UNFOLDED and FLAT-LAID",
    "      on a clear glass tray or acrylic platter, front facing the camera,",
    "      so every printed graphic, embroidered detail, text, and pattern is",
    "      visible from collar to hem at FULL SIZE and SHARP focus. The",
    "      printed/embroidered area on the garment is the focal point of the",
    "      whole frame — render it photographically, not as a stylized",
    "      reinterpretation. Reproduce every word, every character, every",
    "      illustration exactly as in the references. Do NOT fold, stack,",
    "      crumple, or partially obscure the garment. If the set has multiple",
    "      pieces (top + bottom), lay them side by side — both fully visible,",
    "      both fronts facing up. A soft frosted glass panel behind for depth,",
    "      sitting strictly behind the garment with no overlap onto its print.",
    "    • Footwear → a low glass platform beneath plus a vertical frosted",
    "      glass panel behind for depth.",
    "- These glass staging elements must have real glass physics: subtle",
    "  refraction of the background through them, defined edges, soft",
    "  highlights along the upper rim, gentle inner reflections.",
    "- Glass staging elements (shelves, panels, trays, partitions) sit BEHIND",
    "  or BESIDE the product. They must NEVER cover, overlap, or pass in",
    "  front of any printed text, embroidered character, graphic illustration,",
    "  or pattern that appears on the product itself. Every decoration on the",
    "  product remains fully visible and unobstructed.",
    "- A subtle atmospheric haze and gentle bloom around bright areas",
    "  reinforce the soft, layered, glass-like feel of the whole scene.",
    "- Together with the bubble callouts, this staging creates layered",
    "  glassmorphism across the entire image — never just on the callouts.",
    "",
    "Composition — the PRODUCT is the unquestionable hero:",
    "- Large and dominant, occupying 55–65% of frame height, fully in frame.",
    "- Centered or slightly off-center, three-quarter angle, slightly tilted.",
    "- Photoreal magazine quality. Use enough depth of field that the ENTIRE",
    "  product — and every printed text, graphic, embroidery, and pattern on",
    "  it — stays in sharp focus. Background scene may be softened, but never",
    "  the product itself.",
    "",
    "Typography — ONE single headline only. NO subtitle, NO tagline:",
    "- HEADLINE: SHORT product name, 2–3 words MAX (prefer 2). Distill from",
    "  the description; never paste the full SKU. Set in a beautiful editorial",
    "  serif with subtle weight variation between words, generous letter-",
    "  spacing, in a near-black or deep tone that reads cleanly against the",
    "  scene. Placed in prominent negative space beside the product.",
    "- DO NOT add any tagline, subtitle, descriptor line, product type label,",
    "  size/volume label, or secondary text beneath the headline. The headline",
    "  stands alone. All product attributes belong inside the glass bubbles.",
    "- CRITICAL: the headline appears ONCE and ONLY ONCE in the entire image.",
    "  NEVER duplicate it, NEVER render it twice in different colors.",
    "- The headline sits DIRECTLY on the background. It is NOT contained in",
    "  any frosted glass card or panel.",
    "",
    "Glass bubble callouts — supporting glassmorphism element:",
    "- Exactly 2–3 small frosted glass BUBBLES (rounded blob, teardrop, or",
    "  oval shapes — NOT rectangular cards) float asymmetrically around the",
    "  product.",
    "- Each bubble must read as REAL TRANSPARENT GLASS:",
    "    • Visibly transparent center showing the blurred refracted background.",
    "    • A sharp curved highlight along the upper edge.",
    "    • A softer secondary highlight along the lower-left edge.",
    "    • A thin, clearly-defined outer rim — the bubble must have a visible",
    "      glass edge, not fade into the background.",
    "    • A soft drop shadow with a small sliver of light beneath.",
    "- Bubble highlights must be SOFT, ROUND specular catches like real light",
    "  on glass. DO NOT render star-shaped sparkles, four-pointed sparkle",
    "  crosses, lens flares, twinkle effects, or fairy-magic glow. This is",
    "  editorial product photography, not Y2K graphics.",
    "- Each bubble contains a small '+' marker followed by ONE short attribute",
    "  in 1–3 words (e.g. '100% Cotton', 'Long Lasting', 'Matte Finish').",
    "  Text is crisp and unblurred, set in a clean modern sans-serif, dark gray.",
    "- Distribute bubbles asymmetrically — never symmetric corners. Vary",
    "  their sizes slightly. Keep them small and supporting; they must not",
    "  compete with the product.",
    "- Bubbles are placed in the negative space AROUND the product. They",
    "  must NEVER overlap the product, sit in front of any printed graphic,",
    "  text, or embroidered element on the product, or cast their drop",
    "  shadow onto the printed area. Maintain a clear gap between every",
    "  bubble and the product silhouette.",
    "",
    "Palette: bright and airy, with one dominant accent hue drawn from the",
    "product or its theme. Tonally unified across scene, type, and bubbles.",
    "",
    "Render the product faithfully from the attached reference photos —",
    "accurate color, shape, branding, proportions, fully and prominently shown.",
    "Every printed text, embroidered character, graphic illustration, and",
    "pattern visible on the product in the references MUST be reproduced",
    "exactly: character-for-character, color-for-color, position-for-position.",
    "If you cannot reproduce a graphic faithfully, leave it blank rather than",
    "substituting a different one. Do not invent product details.",
    "",
    "CRITICAL — Language rule:",
    languageRule,
    "",
    "Style references: premium consumer-goods advertising, modern lifestyle",
    "brand campaigns with layered glass staging, editorial product posters.",
    "",
    "Output exactly ONE image. No watermarks, no fake logos, all text spelled",
    "correctly.",
    "",
    "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
    "The glassmorphism scene is YOUR creative work. The product itself is",
    "NOT. Apply the two-photographers metaphor: the product in the output is",
    "the SAME PHYSICAL ITEM as the reference, photographed by a professional",
    "in better conditions. The atmospheric scene, glass staging, bubbles,",
    "props, palette, and lighting are yours to compose. The product's",
    "silhouette, color, material, every printed text, every graphic",
    "illustration, every embroidered character, every pattern, every button,",
    "seam, label, hem, and hardware element is FIXED — copied from the",
    "reference, never re-imagined. Run the 5-point identity check from the",
    "ENHANCEMENT block one final time before committing pixels: silhouette,",
    "color, prints, material, features. If any drift, restore the reference's",
    "identity first.",
    "",
    "Product description:",
    '"""',
    trimmed,
    '"""',
  ].join("\n");
}

export async function generateInfographic({
  images,
  description,
  aspectRatio = "3:4",
  style = "glass",
  language = "en",
}: InfographicInput): Promise<EditResult> {
  if (images.length === 0) {
    throw new Error("At least one product image is required.");
  }
  if (images.length > 4) {
    throw new Error("Up to 4 product images are supported.");
  }

  const parts: Part[] = images.map((img) => ({
    inlineData: { mimeType: img.mimeType, data: img.base64 },
  }));
  parts.push({ text: buildInfographicPrompt(description, style, language) });

  const response = await ai.models.generateContent({
    model: INFOGRAPHIC_MODEL,
    contents: [{ role: "user", parts }],
    config: {
      responseModalities: ["IMAGE"],
      imageConfig: { aspectRatio, imageSize: "2K" },
    },
  });

  return extractImage(response);
}
