import { GoogleGenAI, type Content, type Part } from "@google/genai";
import {
  INFOGRAPHIC_STYLES,
  INFOGRAPHIC_LANGUAGES,
  type InfographicStyle,
  type InfographicLanguage,
} from "./infographicStyles";

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  throw new Error("GEMINI_API_KEY is not set in environment");
}

export const ai = new GoogleGenAI({ apiKey, vertexai: true });

export const IMAGE_MODEL = "gemini-3-pro-image-preview";
export const INFOGRAPHIC_MODEL = "gemini-3-pro-image-preview";

export type Turn = {
  role: "user" | "model";
  text?: string;
  imageBase64?: string;
  imageMimeType?: string;
};

export type EditResult = {
  imageBase64: string;
  mimeType: string;
  text?: string;
};

export type InlineImage = {
  base64: string;
  mimeType: string;
};

export type InfographicAspect = "1:1" | "3:4" | "4:3" | "9:16" | "16:9";

export {
  INFOGRAPHIC_STYLES,
  INFOGRAPHIC_LANGUAGES,
  type InfographicStyle,
  type InfographicLanguage,
};

export type InfographicInput = {
  images: InlineImage[];
  description?: string;
  aspectRatio?: InfographicAspect;
  style?: InfographicStyle;
  language?: InfographicLanguage;
};

function turnToContent(turn: Turn): Content {
  const parts: Part[] = [];
  if (turn.imageBase64) {
    parts.push({
      inlineData: {
        mimeType: turn.imageMimeType ?? "image/png",
        data: turn.imageBase64,
      },
    });
  }
  if (turn.text) parts.push({ text: turn.text });
  return { role: turn.role, parts };
}

function extractImage(
  response: Awaited<ReturnType<typeof ai.models.generateContent>>,
): EditResult {
  const parts = response.candidates?.[0]?.content?.parts ?? [];
  let imageBase64: string | undefined;
  let mimeType = "image/png";
  let text: string | undefined;

  for (const part of parts) {
    if (part.inlineData?.data) {
      imageBase64 = part.inlineData.data;
      if (part.inlineData.mimeType) mimeType = part.inlineData.mimeType;
    } else if (part.text) {
      text = (text ? text + "\n" : "") + part.text;
    }
  }

  if (!imageBase64) {
    throw new Error(
      text
        ? `Gemini returned no image. Message: ${text}`
        : "Gemini returned no image (likely blocked by safety filters).",
    );
  }

  return { imageBase64, mimeType, text };
}

export async function editImage(turns: Turn[]): Promise<EditResult> {
  const contents = turns.map(turnToContent);

  const response = await ai.models.generateContent({
    model: IMAGE_MODEL,
    contents,
  });

  return extractImage(response);
}

const LANGUAGE_RULE: Record<InfographicLanguage, string> = {
  en: [
    "Write all on-image LAYOUT text — the titles, headlines, callout labels,",
    "captions, taglines, feature names, units, and CTA copy that YOU add to",
    "the design — in English. Use natural, native English marketing phrasing.",
    "Numbers and universal symbols are fine.",
    "",
    "CRITICAL EXCEPTION — text printed ON the product itself stays EXACTLY",
    "as in the reference photo, in whatever language was printed on the",
    "package. Do NOT translate package text, brand names, slogans, label",
    "text, embroidered text, garment prints, care labels, or any text that",
    "is part of the physical product's printed surface. If the package says",
    "'Алюминиевая Фольга' in Russian Cyrillic, the output package ALSO says",
    "'Алюминиевая Фольга' in Russian Cyrillic — never 'ALUMINUM FOIL' in",
    "English. If a t-shirt's print reads 'PLAY × HONEY CAVE' in English,",
    "the output keeps that exact English text — never translated to Russian.",
    "Product text is part of the product's identity. Translating it destroys",
    "the product. Only LAYOUT text (typography you add around the product)",
    "follows the layout language. Product surface text is FROZEN per the",
    "FIDELITY and PRINTED DESIGN blocks.",
  ].join("\n"),
  ru: [
    "Write all on-image LAYOUT text — the titles, headlines, callout labels,",
    "captions, taglines, feature names, units, and CTA copy that YOU add to",
    "the design — in Russian (Русский язык). Use natural, native Russian",
    "marketing phrasing — not transliteration. Numbers and universal symbols",
    "are fine.",
    "",
    "CRITICAL EXCEPTION — text printed ON the product itself stays EXACTLY",
    "as in the reference photo, in whatever language was printed on the",
    "package. Do NOT translate package text, brand names, slogans, label",
    "text, embroidered text, garment prints, care labels, or any text that",
    "is part of the physical product's printed surface. If a t-shirt's print",
    "reads 'PLAY × HONEY CAVE' in English, the output keeps that exact",
    "English text — never translated to Russian. Product text is part of",
    "the product's identity. Translating it destroys the product. Only",
    "LAYOUT text (typography you add around the product) follows the layout",
    "language. Product surface text is FROZEN per the FIDELITY and PRINTED",
    "DESIGN blocks.",
  ].join("\n"),
  uz: [
    "Write all on-image LAYOUT text — the titles, headlines, callout labels,",
    "captions, taglines, feature names, units, and CTA copy that YOU add to",
    "the design — in Uzbek written in the modern Latin alphabet (O'zbek",
    "tili, lotin alifbosi). Use natural, native Uzbek marketing phrasing —",
    "not transliteration of English or Russian. Numbers and universal",
    "symbols are fine.",
    "",
    "CRITICAL EXCEPTION — text printed ON the product itself stays EXACTLY",
    "as in the reference photo, in whatever language was printed on the",
    "package. Do NOT translate package text, brand names, slogans, label",
    "text, embroidered text, garment prints, care labels, or any text that",
    "is part of the physical product's printed surface. If the package says",
    "'Алюминиевая Фольга' in Russian, the output ALSO says 'Алюминиевая",
    "Фольга' in Russian — never translated to Uzbek. Product text is part",
    "of the product's identity. Translating it destroys the product. Only",
    "LAYOUT text (typography you add around the product) follows the layout",
    "language. Product surface text is FROZEN per the FIDELITY and PRINTED",
    "DESIGN blocks.",
  ].join("\n"),
};

const COMPOSITING_DIRECTIVE = [
  "OPERATING MODE — this is an IMAGE EDIT, not an image generation:",
  "You are EDITING the attached reference photo, not generating a new product",
  "from scratch. Take the attached product photo as the source for what the",
  "PRODUCT IS — its identity, materials, prints, graphics, hardware, color,",
  "and silhouette. Reproduce all of those product details bit-identically.",
  "",
  "The PRODUCT is frozen. The PHOTOGRAPH is not.",
  "",
  "Specifically, you MUST preserve from the reference (the product layer):",
  "- Every printed word, logo, label, and slogan on the product surface.",
  "- Every graphic illustration, embroidered character, applique, or 3D",
  "  decorative element — exact line weight, pose, color, position.",
  "- Every pattern, print, weave, grain, and surface texture.",
  "- The product's color, shape, silhouette, proportions, and material.",
  "- Every real feature: buttons, zippers, seams, hems, hardware, joints,",
  "  bolts, mounts, clasps, trim — same count, same shape, same place.",
  "",
  "But you MUST DISCARD from the reference (the photograph layer):",
  "- The original background entirely — concrete floors, walls, doors,",
  "  rooms, outdoor surfaces, bystanders, the photographer's hand or foot,",
  "  any environmental context. None of it appears in the output.",
  "- The original lighting DIRECTION (which side of the product was lit,",
  "  where shadows fell) and any harsh raw-flash artifacts. You may relight",
  "  the product to match the new scene's key-light direction and intensity.",
  "  HOWEVER: the product's HUE and SATURATION stay identical to the",
  "  reference — re-lighting changes brightness and shadow placement, NOT",
  "  color. Do NOT 'correct white balance', 'neutralize color cast', or",
  "  'adjust' the product's color in any way.",
  "- The original camera angle ONLY if it is severely broken (the product",
  "  on its side when it should be upright, rotated more than 30° from a",
  "  usable composition, or so off-axis that the main features are not",
  "  visible). For ALL OTHER reference photos — including ones with mild",
  "  low-angle, slightly tilted, or unconventional viewpoints — PRESERVE",
  "  THE REFERENCE'S CAMERA ANGLE EXACTLY. Same rotation, same viewpoint,",
  "  same 3D orientation, same perspective. Do NOT 're-pose to a clean",
  "  three-quarter studio angle' as a default — that re-pose is reserved",
  "  for genuinely broken reference photos. When in doubt, match the",
  "  reference's angle. The user's expectation is that the product looks",
  "  the same as in the photo they uploaded, including the angle.",
  "",
  "Mental model: this is a Photoshop composite with three layers:",
  "  1. PRODUCT layer — same physical product, RE-PHOTOGRAPHED in a studio.",
  "     Identity preserved bit-identically; lighting and angle re-shot.",
  "  2. SCENE layer — the styled background you compose around it.",
  "  3. TEXT layer — the typography and callouts.",
  "Layer 1's IDENTITY is frozen. Its photography is not. Layers 2 and 3",
  "are yours to author.",
  "",
  "If the reference photo shows the product against a messy real-world",
  "background (concrete, dirt, clutter, a person's foot, a kitchen counter,",
  "a packing box), you MUST replace that background entirely with the styled",
  "scene this prompt calls for. NEVER paste the original photo as-is into",
  "the layout — that is a failure mode, not the goal. The goal is to make",
  "it look as if a professional photographer re-shot the same product in a",
  "proper studio ten minutes after the reference was taken.",
  "",
  "If at any point you feel the urge to 'clean up', 'simplify', 're-balance',",
  "or 're-render' anything ON the product surface itself — buttons, prints,",
  "labels, hardware — you are working on the wrong layer. Stop and switch",
  "to Layers 2 or 3, or to re-lighting the product within Layer 1.",
  "",
].join("\n");

const ENHANCEMENT_BLOCK = [
  "PHOTOGRAPHIC ENHANCEMENT — re-photograph the product, never re-design it:",
  "The reference photo may be low quality: phone snapshot, dim or color-cast",
  "lighting, motion blur, soft focus, cluttered background, wrinkled fabric,",
  "dust, lint, smudges, glare, fingerprints, harsh shadows, awkward angle.",
  "Treat the reference as the SOURCE OF TRUTH for what the product IS, but",
  "as a STARTING POINT for how the product is photographed. Render the",
  "product in the output as if it were freshly captured by a professional",
  "product photographer in a high-end studio:",
  "- Tack-sharp pixel-level focus and high resolution across the entire",
  "  product surface.",
  "- Even, flattering studio-quality lighting that matches the scene's key-",
  "  light direction. Clean specular highlights with shape, soft fill,",
  "  controlled rim light, no harsh raw flash.",
  "- Lighting only — relight the product to match the new scene's key-",
  "  light direction and intensity. The product may appear brighter or",
  "  darker overall, but its HUE and SATURATION stay identical to the",
  "  reference. Do NOT 'correct', 'neutralize', 'adjust', 'rebalance', or",
  "  'restore' the product's color in any way. If the reference shows the",
  "  product as a specific shade — including any warmth, coolness, or",
  "  tint from the original photo's environment — the output shows that",
  "  EXACT same shade. You are not the white-balance authority on this",
  "  product. Whatever color the reference shows IS the product's color.",
  "- Surface cleanup — remove ONLY these specific photographic artifacts",
  "  that are clearly not part of the product: free-floating hair on the",
  "  fabric, visible dust specks in the air or on the lens, obvious",
  "  fingerprint smudges on glass/screens, motion blur. That is the",
  "  ENTIRE allowed cleanup list. You may NOT remove, smooth, simplify,",
  "  or 'clean up' anything else, including: wrinkles in fabric, creases,",
  "  texture variation, color variation, surface irregularities,",
  "  imperfect stitching, slight asymmetry, joint discoloration, scuffs",
  "  on hardware, or any feature you cannot positively identify as a",
  "  photographic artifact. When in doubt, preserve. A wrinkle you leave",
  "  alone is recoverable; a feature you 'cleaned up' is gone.",
  "- Keep ALL real product details: every button, zipper, seam, stitch,",
  "  label, tag, hardware element, joint, screw, bolt, mount, panel,",
  "  color block, material patch, and decorative element appears in the",
  "  output at the SAME position, shape, color, count, and proportion as",
  "  in the reference. Count buttons in the reference; the output has the",
  "  same count. Count zippers; same count. Count joints, screws, panels;",
  "  same count. The model must NOT consolidate, simplify, or 'tidy' the",
  "  product's feature inventory.",
  "- Replace the reference's cluttered or messy background entirely with the",
  "  styled scene this prompt calls for.",
  "- Straighten the product's pose ONLY if it is severely tilted (>30°",
  "  off-axis from a usable composition). For mild angle imperfections,",
  "  unconventional viewpoints, or low-angle shots that still show the",
  "  product clearly, PRESERVE the reference's pose exactly — same",
  "  orientation, same rotation, same viewpoint. Flatten a garment ONLY",
  "  if it is severely bunched in a way that hides printed graphics.",
  "  Otherwise, match the reference's presentation as closely as possible.",
  "",
  "Enhancement is NEVER a license to alter what the product IS. Do NOT use",
  "this clause as cover for redrawing, simplifying, restyling, recoloring,",
  "or substituting:",
  "- Printed text, character graphics, embroidered designs, pattern motifs,",
  "  surface prints, brand marks — preserve them exactly as in the reference.",
  "- The product's exact reference color, shape, silhouette, proportions, or material.",
  "- Any real, intentional product feature (zipper, button, seam, label,",
  "  trim, hardware, branded element).",
  "",
  "TWO-PHOTOGRAPHERS METAPHOR — the rule that resolves all ambiguity:",
  "Picture the reference photo as taken by an amateur with a phone in poor",
  "lighting. Picture the output as the SAME PRODUCT photographed by a",
  "professional ten minutes later in a proper studio. Between those two",
  "photographs, NOTHING about the product has been touched. The buttons are",
  "in the same places. The cut and silhouette of the garment are identical.",
  "The print on the chest is the SAME print, with the SAME line weight, the",
  "SAME color, the SAME character design in the SAME pose. The label says",
  "the SAME words. The fabric is the SAME fabric, the same weave, the same",
  "color. The pockets, seams, hems, zippers, hardware are in the same",
  "places, same count, same shape. Only the photography changed.",
  "",
  "If you find yourself wanting to make the product 'cleaner', 'more",
  "balanced', 'more elegant', 'more readable', or 'better designed' — STOP.",
  "That instinct is wrong. The product is already finished. Your job is the",
  "PHOTO, not the product.",
  "",
  "IDENTITY CHECK — perform this before finalizing the output:",
  "Mentally place the rendered product next to the reference photo. The two",
  "must be recognizable as the SAME PHYSICAL ITEM — the same SKU pulled off",
  "the same shelf. Run through this checklist:",
  "  1. Same silhouette and proportions? (cut, fit, length, width)",
  "  2. Same color, hue, and saturation as in the reference? No 'true",
  "     color' inference, no white-balance correction, no tint shift.",
  "     The product's color in the output matches the reference exactly,",
  "     even if the reference's color was affected by the original photo's",
  "     lighting. Whatever color you saw in the reference IS the answer.",
  "  3. Same printed graphics in the same positions? (line weight, character",
  "     design, pose, palette unchanged)",
  "  4. Same material and texture? (cotton stays cotton, denim stays denim,",
  "     plastic stays plastic, with the same weave/grain visible)",
  "  5. Same real features in the same places? (every button, zipper, label,",
  "     seam, hem, pocket, strap, hardware element)",
  "If ANY answer is no, you have redesigned the product. Restore the",
  "reference's identity and re-render.",
  "",
].join("\n");

const FIDELITY_BLOCK = [
  "ABSOLUTE PRODUCT FIDELITY — read first, applies above all other instructions:",
  "The attached reference photo(s) show the EXACT product. Treat it as a fixed,",
  "immutable asset that must appear in the output IDENTICAL to the reference.",
  "You may relight, reposition, rotate, scale, or replace its background. You",
  "may NOT, under ANY circumstance, alter:",
  "- Printed text on the product (logos, slogans, labels) — every word must",
  "  match character-for-character. If the t-shirt says 'MY FRIEND', the",
  "  output t-shirt must say 'MY FRIEND', not nothing and not something else.",
  "- Patterns, prints, or surface designs (sprinkles, stripes, dots, florals,",
  "  camo, plaid). Preserve density, color, scale, and placement exactly.",
  "- Embroidered, applique, fluffy, or 3D decorative elements — preserve their",
  "  exact shape, texture, character design, pose, and position.",
  "- Printed graphics or character illustrations on the product. Do NOT",
  "  redraw, simplify, restyle, or substitute with a generic version. Match",
  "  the original character's pose, expression, color, and rendering style.",
  "- The product's color, shape, silhouette, proportions, or material.",
  "- Any care labels, brand marks, tags, stitching, or trim.",
  "",
  "If you cannot reproduce a printed graphic faithfully, leave it blank rather",
  "than inventing a different one. A missing detail is recoverable; a wrong",
  "detail is a failure. The product in the output MUST be recognizable as the",
  "SAME PHYSICAL ITEM as the reference photo, not a 'similar' product.",
  "",
  "- FULL PRODUCT VISIBILITY — non-negotiable: every decorative element on",
  "  the product (printed text, embroidered characters, pattern motifs,",
  "  graphic prints, brand marks) must be plainly visible at full size. Do",
  "  not hide any portion of a graphic by folding, cropping, stacking,",
  "  perspective angle, or scene props. If the reference photo shows the",
  "  product flat-laid, the output is flat-laid. If on a hanger, on a hanger.",
  "  If on a model, on a model. Match the reference's presentation mode.",
  "",
].join("\n");

const PRINTED_DESIGN_BLOCK = [
  "PRINTED DESIGN PRESERVATION — read with extreme care, this is the rule",
  "the model most often violates:",
  "",
  "Anything PRINTED, PHOTOGRAPHED, or DRAWN on the product surface in the",
  "reference (packaging artwork, garment graphics, label illustrations,",
  "character prints, sticker designs, embroidered patches, brand badges,",
  "wax seals) is PHOTOGRAPHIC CONTENT — pixels you carry over from the",
  "reference, NOT artwork you redesign. Treat printed designs as if they",
  "were photos pasted onto the product surface: copy them across, do not",
  "re-author them. The reference photo may be low-quality, but the printed",
  "design IS the product's identity at full fidelity.",
  "",
  "FOR PACKAGING (boxes, bottles, jars, tubes, wrappers, sleeves, pouches,",
  "cartons, foil rolls, food packs, beauty packs, cleaning packs):",
  "- The exact illustrations, photos, characters, badges, wax seals, and",
  "  graphics from the reference appear on the package in the output, in the",
  "  SAME positions, SAME colors, SAME drawing style, SAME line weight.",
  "- The exact dominant background color of the package is preserved. If the",
  "  reference shows a RED+YELLOW box, the output shows a RED+YELLOW box —",
  "  NOT cream+yellow, NOT orange+yellow, NOT any other variation.",
  "- Logos and brand marks render at the SAME size, SAME position, SAME",
  "  color as in the reference. A logo on a yellow strip stays exactly there",
  "  — do not move it, do not recolor it, do not redraw the logo mark.",
  "- Decorative elements (wax seals, ribbons, badges, certification stamps,",
  "  spec callouts) appear in the SAME position with the SAME design — do",
  "  not substitute a red wax seal for a different shape or color, do not",
  "  swap a photographic illustration for a hand-drawn one or vice versa.",
  "- The product photo / illustration printed on the package (if any) is",
  "  preserved exactly — same subject, same drawing style, same colors.",
  "- DO NOT 'clean up', 'modernize', 'simplify', 'redesign', or",
  "  'professionalize' the package design. The package's existing design IS",
  "  the design. The reference photo being a phone snapshot does NOT mean",
  "  the package is rough — it means the photography is rough.",
  "",
  "FOR APPAREL WITH PRINTS (t-shirts, hoodies, sweatshirts, tank tops,",
  "pajamas, anything with a graphic on the chest, back, or sleeves):",
  "- The exact graphic / character / illustration on the garment is preserved",
  "  pixel-faithfully — same subject, same pose, same expression, same",
  "  rendering style (photographic stays photographic, illustrated stays",
  "  illustrated, painted stays painted).",
  "- The exact spatial relationship of TEXT to GRAPHIC is preserved. If text",
  "  arches OVER a character and other text sits BELOW the character, the",
  "  output keeps that wraparound layout — never collapses it into a single",
  "  line of clean caption text below the graphic. Curved text stays curved.",
  "  Above-and-below stays above-and-below.",
  "- The exact STYLE of printed text is preserved. Distressed / painted /",
  "  brush / hand-drawn / graffiti lettering stays distressed / painted /",
  "  brush / hand-drawn / graffiti — never substituted with a clean modern",
  "  sans-serif. If the lettering looks like white paint dripping on the",
  "  shirt in the reference, the output also has white-paint-dripping",
  "  lettering, not crisp Helvetica.",
  "- DO NOT add accessories, props, or embellishments the reference does not",
  "  show. If the bear in the reference has no ribbon, the output bear has",
  "  no ribbon. If the bear has a brown bow, the output bear has the SAME",
  "  brown bow — not a different bow, not a removed bow.",
  "- DO NOT remove text or graphic elements that the reference includes.",
  "  Every word visible on the print is preserved. Every illustrated element",
  "  is preserved.",
  "",
  "EXPLICIT FAILURE EXAMPLES — these are exactly what NOT to do:",
  "",
  "Failure 1 — packaging redesign:",
  "  Reference: a red and yellow foil-roll box, with 'Алюминиевая Фольга' in",
  "  red distressed lettering running along the side, a mountain-logo brand",
  "  mark on a yellow strip, a red round wax seal reading 'ЭКСТРА СИЛЬНЫЙ',",
  "  and a small photograph of fish-with-vegetables in the corner.",
  "  WRONG output: a cream-and-yellow foil-roll box, with 'ФОЛЬГА' in clean",
  "  blue sans-serif on the side, a redrawn mountain logo, a different wax",
  "  seal, and a hand-drawn fish-with-vegetables illustration replacing the",
  "  photograph. The colors are wrong, the type style is wrong, the",
  "  illustration medium is wrong, the layout is rebuilt. THIS IS A COMPLETE",
  "  REDESIGN AND IS FORBIDDEN.",
  "  RIGHT output: the SAME red-and-yellow box, SAME 'Алюминиевая Фольга'",
  "  in the SAME red distressed lettering in the SAME position, SAME",
  "  mountain logo on the SAME yellow strip, SAME red wax seal, SAME",
  "  photographic fish-with-vegetables image. Only the photography of the",
  "  box has changed — better lighting, better background, cleaner angle.",
  "  The box itself is identical to the reference.",
  "",
  "Failure 2 — apparel print collapse:",
  "  Reference: a red t-shirt with 'PLAY × HONEY' in distressed white",
  "  lettering arched ABOVE a photographic teddy bear, and 'CAVE' in",
  "  matching distressed white lettering BELOW the bear. Three distinct",
  "  layers: top text arc, bear in middle, bottom text.",
  "  WRONG output: a red t-shirt with the bear alone in the center, no text",
  "  arching above it, and 'PLAY x HONEY CAVE' as a single line of clean",
  "  small sans-serif text beneath the bear. The arched layout is gone, the",
  "  distressed lettering is gone, the spatial relationship is gone, and the",
  "  bear may have an added ribbon that wasn't in the reference. THIS IS A",
  "  PRINT REDESIGN AND IS FORBIDDEN.",
  "  RIGHT output: the SAME red t-shirt, SAME 'PLAY × HONEY' arched ABOVE",
  "  the SAME bear in the SAME pose with the SAME (or no) accessories, SAME",
  "  'CAVE' BELOW the bear, SAME distressed white lettering style. Only the",
  "  photography has changed — better lighting, cleaner background.",
  "",
  "If you cannot reproduce a printed design exactly, leave that area BLANK",
  "or as a flat color rectangle. A blank area is recoverable; a redesigned",
  "area is a failure that the user will reject the entire image for.",
  "",
  "Self-check before rendering: take the printed design from the reference",
  "and the printed design from your output, and ask 'would a customer who",
  "owns this product look at the output and say yes, that is my product?'",
  "If the answer is 'similar but not the same', the printed design has",
  "drifted and must be restored.",
  "",
].join("\n");

function buildInfographicPrompt(
  description: string | undefined,
  style: InfographicStyle,
  language: InfographicLanguage,
): string {
  const trimmed = description?.trim() ?? "";
  const languageRule = LANGUAGE_RULE[language];
  const hasDescription = trimmed.length > 0;

  const copyDirective = hasDescription
    ? [
        "COPY SOURCE — where every word on the image must come from:",
        "A product description has been provided at the bottom of this prompt.",
        "Treat that description as the SINGLE SOURCE OF TRUTH for every word",
        "rendered on the image — the product name, headline, feature labels,",
        "callout captions, taglines, technical specs, benefit titles, CTA",
        "wording, all of it. Extract the relevant phrases from the description",
        "and place them in the slots this style calls for. Do not paste the",
        "description verbatim — distill it into short, well-crafted on-image",
        "copy. Do not invent product names, features, claims, certifications,",
        "or numbers that cannot be derived from the description.",
        "",
        "ABSOLUTE RULE — illustrative phrases are NEVER rendered:",
        "Anywhere in this prompt where a sample phrase appears inside single",
        "or double quotes within an 'e.g.', 'such as', or parenthetical",
        "example — for instance 'Model 2025', 'Product', 'Care', 'Size Chart',",
        "'Unisex ⌄', 'Premium ⌄', 'JUST DO IT.', 'Move Forward.', 'Other",
        "Colors →', 'See More →', 'PURE', 'QUIET LUXURY', 'Sneakers',",
        "'Headphones', 'Bottle', 'TWISTRUSS', 'AHAR PLUS', 'ProControl',",
        "'Wide Size Range', '35–42', '128 GB', '500 ml', 'model @2025',",
        "'100% Cotton', 'Long Lasting', 'Matte Finish' — those words are",
        "EXAMPLES OF FORMAT ONLY and must NEVER appear on the image. Replace",
        "every one of them with wording you derive from the actual product",
        "description for this generation.",
      ].join("\n")
    : [
        "COPY SOURCE — where every word on the image must come from:",
        "No product description was provided. Read the product carefully from",
        "the reference photos — identify its category, materials, visible",
        "features, brand name (only if clearly printed), and the most likely",
        "3–5 selling points. Then write all on-image copy yourself in",
        "confident, benefit-led marketing phrasing. Do not invent specific",
        "numbers, certifications, or factual claims you cannot verify from",
        "the photos themselves.",
        "",
        "ABSOLUTE RULE — illustrative phrases are NEVER rendered:",
        "Anywhere in this prompt where a sample phrase appears inside single",
        "or double quotes within an 'e.g.', 'such as', or parenthetical",
        "example — for instance 'Model 2025', 'Product', 'Care', 'Size Chart',",
        "'JUST DO IT.', 'PURE', 'QUIET LUXURY', 'Sneakers', 'TWISTRUSS',",
        "'Wide Size Range', '128 GB' — those words are EXAMPLES OF FORMAT",
        "ONLY and must NEVER appear on the image. Replace every one of them",
        "with wording you author for this specific product.",
      ].join("\n");

  if (style === "cards") {
    return [
      FIDELITY_BLOCK,
      PRINTED_DESIGN_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE marketplace infographic in the",
      "style used on Wildberries / Ozon premium product listings: a 2×2 grid of",
      "four separate rounded-corner panels on a light neutral background, sharing",
      "a single cohesive color story derived from the product itself.",
      "",
      "SINGLE-VIEW RULE — read this first, it overrides everything below:",
      "Re-photograph the product ONCE — a clean, well-lit hero view in a studio",
      "(three-quarter angle, straight-on, or whatever best shows the product's",
      "structure). That ONE re-photographed view is the source for ALL FOUR",
      "PANELS. Every other panel either:",
      "  (a) shows the SAME hero view at different scale/framing/lighting/crop,",
      "      or",
      "  (b) shows a tight ZOOM CROP into a specific region of that hero view.",
      "You MAY NOT invent additional viewing angles — no rotated views, no",
      "imagined back/side/interior shots, no second photoshoot. If multiple",
      "reference photos are provided, you may use them as additional source",
      "views; if only one reference is provided, every panel derives from your",
      "single re-photographed hero. The product's identity (proportions,",
      "joints, hardware, every structural element) must be IDENTICAL across",
      "every panel because every panel is the same physical item.",
      "",
      "Panel layout:",
      "- Top-left (HERO): the re-photographed hero view at full size, with the",
      "  product's name as oversized soft-tone display typography behind/around",
      "  it. One small floating chip with a key fact derived from the description.",
      "  Light background.",
      "- Top-right (SPECS / FEATURES): 4 small sub-tiles inside this panel,",
      "  each a TIGHT ZOOM CROP into a different region of the SAME hero view —",
      "  a corner joint, a foot detail, the rail texture, the hinge mechanism.",
      "  These are crops of the hero, not new photos. Do NOT invent macro",
      "  detail that isn't visible in the hero. Mix of dark-background and",
      "  light-background sub-tiles for visual variety.",
      "- Bottom-left (MODES / USE CASES): a darker, moodier rendering of the",
      "  SAME hero view (re-lit with dramatic studio lighting, dark background)",
      "  showing the product in lifestyle context (e.g. with clothes hanging",
      "  on it, in a dim room). The product's silhouette, joints, hardware,",
      "  and proportions match the hero exactly. Two short labels with one-",
      "  line captions placed in negative space.",
      "- Bottom-right (BENEFITS): the SAME hero view at a different framing",
      "  or zoom (NOT a new angle), on a light panel. 3 stacked benefit blocks",
      "  (bold short title + 2–3 line caption) authored from the description.",
      "",
      "IDENTITY ACROSS PANELS — non-negotiable:",
      "Every panel shows the same physical product. Count: same number of rails,",
      "bars, joints, feet, screws, hinges, panels, buttons, seams. Materials:",
      "same metal finish, same plastic color, same wood grain. Hardware: same",
      "joint mechanism (if input has a metal disc with bolts, output has a",
      "metal disc with bolts — never substitute a different joint type). If",
      "you find yourself drifting toward a 'generic version' of this product",
      "category — STOP. The output must be the user's specific item, not a",
      "stock photo of a similar item.",
      "",
      "Typography: bold sans-serif. Strong size hierarchy — huge, medium, small.",
      "Headline weight heavy; body weight regular. Labels are short (1–3 words).",
      "",
      "Strict no's: no circular icon badges with thin-line icons, no arrow",
      "callouts pointing at a centered product, no rainbow color accents, no",
      "stock-template feel.",
      "",
      "PANEL BOUNDARY ENFORCEMENT — read this rule first, it is the single",
      "most important constraint on this layout:",
      "",
      "The four rounded panels are HARD WINDOWS. Every pixel of every product",
      "image MUST be contained INSIDE one of the four panels. Nothing of the",
      "product — no rod, no bar, no leg, no edge, no shadow of the product",
      "itself, no fragment of the reference photo, no portion of its original",
      "environment — may exist on the canvas OUTSIDE the panel borders.",
      "",
      "Mental model: the four panels are physical photographs lying on a sheet",
      "of plain paper. The paper underneath them is empty solid color. If you",
      "lifted any panel off the paper, the area beneath would be blank — not a",
      "copy of the product, not the original photo, not a backdrop layer, not",
      "anything. The panels are the ONLY place the product appears.",
      "",
      "Specifically forbidden — these break the layout:",
      "- The reference photo rendered at ANY opacity (full, faint, ghosted, or",
      "  in between) anywhere on the canvas behind the panels.",
      "- Any portion of the product extending past a panel border — a rod",
      "  poking out, a bar bridging two panels, an edge crossing the seam,",
      "  a leg stretching into the gap.",
      "- The original photograph's environment (concrete, walls, floor,",
      "  weeds, dirt, the photographer's foot, any outdoor/indoor backdrop)",
      "  visible anywhere in the gap zones.",
      "- A 'connecting' visual element of any kind in the gaps between panels.",
      "- Atmospheric haze, blur, gradient, or texture in the gap zones.",
      "- Treating the canvas as a full-bleed product backdrop with the four",
      "  panels as windows or cutouts on top.",
      "",
      "If you find yourself rendering the product as a full-canvas image and",
      "placing the panels on top, STOP. That is the failure mode. The product",
      "is INSIDE each panel as a separate composition — never across panel",
      "borders, never behind them, never around them.",
      "",
      "CONCRETE FAILURE EXAMPLE — this exact failure has happened and must",
      "not happen again:",
      "",
      "Reference photo: a metal drying rack standing on rough outdoor",
      "concrete with weeds growing through the cracks, a painted metal",
      "door behind it, and the photographer's blue shoe visible in the",
      "lower corner of the frame.",
      "",
      "WRONG output: a 2×2 panel layout where each panel shows the rack",
      "in clean studio conditions, BUT a horizontal strip in the middle",
      "of the canvas (between the top row and bottom row of panels)",
      "shows the ORIGINAL reference photo — concrete, weeds, painted",
      "door, photographer's shoe — bleeding through. As if the canvas",
      "itself were the reference photo and the four panels were windows",
      "cut on top of it. THIS IS A CRITICAL LAYOUT FAILURE.",
      "",
      "RIGHT output: a 2×2 panel layout where each panel shows the rack",
      "in clean studio conditions, AND the entire canvas background —",
      "top edge, middle gap, bottom edge, side margins, every pixel that",
      "is NOT inside one of the four panels — is a SOLID FLAT NEUTRAL",
      "COLOR (soft cream / light beige / off-white). The concrete, weeds,",
      "door, and shoe from the reference do not appear anywhere on the",
      "canvas. They exist only in the photo you were given as input;",
      "they have zero presence on the output canvas.",
      "",
      "Mental model: imagine you printed each of the 4 panels as a",
      "physical 4×6 photograph and laid them on a fresh sheet of",
      "cream-colored cardstock. The cardstock underneath was BLANK",
      "before you placed the panels — you did NOT print the reference",
      "photo on the cardstock first, you did NOT use the reference",
      "photo as the cardstock. Lift any panel off the cardstock and",
      "the area beneath is plain cream, with nothing on it.",
      "",
      "The canvas background and the reference photo's environment",
      "are TWO COMPLETELY UNRELATED THINGS. The reference photo's",
      "environment is what you must DISCARD per the COMPOSITING",
      "DIRECTIVE. The canvas background is what you GENERATE FRESH,",
      "from scratch, in solid neutral cream. They never overlap.",
      "",
      "FINAL VISUAL CHECK — perform this before committing pixels:",
      "Look at the canvas. Identify the four rounded-rectangle panels. Look",
      "at every region OUTSIDE those four shapes — the horizontal gap between",
      "top and bottom rows, the vertical gap between left and right columns,",
      "the canvas margins around all four edges. Every one of those gap zones",
      "must be SOLID NEUTRAL COLOR with NOTHING visible in it except the",
      "shadows cast by the panels themselves. If you see any product imagery,",
      "reference-photo content, or environmental texture in any gap zone, the",
      "layout has failed. Restart.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image containing the four panels.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING:",
      "Place the rendered hero panel mentally next to the reference photo.",
      "Same number of structural elements? Same joint type? Same proportions?",
      "Same materials? Same color, hue, and saturation (no white-balance",
      "correction, no tint shift)? Same printed design (packaging artwork,",
      "garment graphics, labels) preserved pixel-faithfully — same colors,",
      "same illustrations, same text style, same spatial layout? If any",
      "answer is no, you've drifted into a redesigned version. Restore the",
      "reference's identity, then propagate that single view across all four",
      "panels.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  if (style === "ticket") {
    return [
      FIDELITY_BLOCK,
      PRINTED_DESIGN_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE split-canvas ticket-stub editorial composition.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print,",
      "graphic, embroidery, color, button, seam stays exactly as in the source).",
      "But the LAYOUT around the product is required to be aggressive and graphic.",
      "You ARE permitted (and required) to do all of the following — these are",
      "SCENE / COMPOSITION operations, not product modifications:",
      "- Build a vertical split background (~60% black on the left, ~40%",
      "  saturated accent color on the right) underneath the product.",
      "- Tilt the product 10–25° from horizontal within the frame (rotation,",
      "  not redraw).",
      "- Position the product so it visually OVERLAPS the seam between the",
      "  two regions and bridges them (placement, not redraw — the seam runs",
      "  behind the product).",
      "- Add the ticket-stub graphics on the right region: barcodes, dotted",
      "  perforation line, decorative low-opacity letterform, etc.",
      "- Add a top nav strip, massive display headline, sub-headline,",
      "  feature list, tagline, body paragraph, and CTA pill in the dark",
      "  region — all overlaid in the SCENE / TEXT layers around the product.",
      "Do all of this. The product appears unchanged; the layout around it is",
      "fully designed.",
      "",
      "STYLE — TICKET STUB EDITORIAL (split-canvas fashion-catalog spread with ticket-design right side):",
      "",
      "COLOR LOCK — zero decision freedom, follow exactly:",
      "  Step 1: Identify the product's dominant color in the reference",
      "    photo (one word — red, blue, green, yellow, orange, pink,",
      "    purple, brown, black, white, gray). If the product is multi-",
      "    colored, pick the color that occupies the largest surface area.",
      "  Step 2: Render the product in the output with EXACTLY that color,",
      "    bit-identical to the reference (same hue, same saturation, same",
      "    value — no shift). All other product colors stay as in the",
      "    reference.",
      "  Step 3: The accent color used for the right-region background MUST",
      "    EQUAL the product's dominant color from Step 1. Same hue, same",
      "    saturation. A red product → red right-region. A blue product →",
      "    blue right-region. No substitution, no contrast, no complementary",
      "    color, no harmonization decision.",
      "  Step 4: Edge case — if the product's dominant color is black,",
      "    white, or a near-neutral gray, the accent becomes a single rich",
      "    saturated hue you may pick (cobalt, emerald, crimson, amber,",
      "    etc.) — but the product itself still renders with its exact",
      "    reference color, never tinted to match the accent.",
      "There is no creative choice. The product's reference color dictates",
      "both the product's output color AND the accent color. If you find",
      "yourself wanting to recolor the product to balance the palette, STOP",
      "— the rule is broken. The accent already equals the product.",
      "",
      "- Background: a vertical asymmetric split — the LEFT ~60% of the canvas is",
      "  pure black or very dark charcoal, the RIGHT ~40% is the accent color",
      "  from the COLOR LOCK above (equal to the product's dominant color). The",
      "  two regions meet at a clean vertical edge running floor to ceiling.",
      "- Ticket stub — defining structural move: the right region is designed as",
      "  a TICKET STUB or ADMISSION CARD, with a real-looking barcode + digits",
      "  at the very top, a second smaller barcode at the bottom, a horizontal",
      "  dotted perforation line near the bottom suggesting it can be torn off,",
      "  and optionally a single MASSIVE letterform glyph (Cyrillic, Latin, or",
      "  whichever the description's language uses) at very low opacity inside",
      "  the ticket as decorative texture.",
      "- Product: photorealistic, dramatically sized, tilted at 10–25° from",
      "  horizontal, OVERLAPPING the seam between the two regions so it visually",
      "  bridges the dark and accent halves. Occupies ~55–70% of canvas height.",
      "  This overlap is the second defining move — the product anchors the",
      "  composition by belonging to both sides at once.",
      "- Top nav strip (across the dark region): a thin row of 3–4 short",
      "  categorical tab-like labels in a light sans-serif. Author the labels",
      "  yourself from product attributes mentioned in the description (or,",
      "  with no description, from the product category). Reads like a",
      "  magazine top nav or a product-page tab bar.",
      "- Display headline: a MASSIVE bold condensed sans-serif word in white",
      "  inside the dark region, all caps, set against the upper-left area —",
      "  the product category in one short word, tightly tracked. Optional",
      "  small period or accent mark after the word for typographic detail.",
      "- Sub-headline: directly beneath, a smaller bold sans-serif label with",
      "  an optional small disclosure caret (e.g. 'Unisex ⌄', 'Premium ⌄').",
      "- Feature list: 2–4 short feature callouts in the dark region beneath",
      "  the sub-headline, each prefixed with a small '⊕' glyph, followed by a",
      "  bold short label and a one-line caption in a lighter weight beneath.",
      "  These are NOT chips — just plain text with a leading plus glyph.",
      "- Tagline + body: at the bottom of the dark region, a short bold tagline",
      "  in white ('JUST DO IT.', 'Move Forward.', or equivalent in the",
      "  description's language) plus a 3–5 line body paragraph in small light-",
      "  weight sans-serif beneath it.",
      "- Inside the ticket: a bold sans-serif model or variant name near the",
      "  top, a small label beneath, then a pill-shaped button in the dark",
      "  color with white text (status or short tagline). Lower in the ticket:",
      "  a key spec callout in oversized bold sans (size range, capacity,",
      "  count) followed by a black pill-shaped CTA button with a right-arrow",
      "  ('Other Colors →', 'See More →', etc.).",
      "- Color: high-contrast pairing — pure black + the LOCKED accent",
      "  (equal to the product's dominant color per the COLOR LOCK) +",
      "  white. The product's own natural colors come through unchanged —",
      "  same red is the same red, same blue is the same blue. The accent",
      "  equals the product; do not touch either. No third accent color,",
      "  no rainbow palette.",
      "- Typography: ONE bold condensed display sans for the massive headline,",
      "  ONE clean modern sans for everything else. No serif, no script, no",
      "  decorative typography.",
      "- Avoid: gradients, atmospheric haze, vignettes, glassy '+' pill chips,",
      "  circular icon badges, decorative botanical props, soft pastel washes,",
      "  oversized backdrop words behind the product, single-color backgrounds",
      "  without the split. This style is graphic, structured, and reads as a",
      "  fashion-catalog spread.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The split-canvas ticket-stub composition is YOUR creative work. The",
      "product itself is NOT. Apply the two-photographers metaphor: the product",
      "in the output is the SAME PHYSICAL ITEM as the reference, photographed",
      "by a professional in better conditions. The black region, the accent",
      "color half, the barcodes, the perforation, the top nav, the headlines",
      "and tagline, the ticket text, and the CTA pill are yours to compose.",
      "The product's silhouette, color, material, every printed text, every",
      "graphic illustration, every embroidered character, every pattern,",
      "every button, seam, label, hem, and hardware element is FIXED — copied",
      "from the reference, never re-imagined. The split seam runs BEHIND the",
      "product, not THROUGH it; the product visually bridges the two halves",
      "but is rendered as a single complete unaltered item. Run the 5-point",
      "identity check from the ENHANCEMENT block one final time before",
      "committing pixels: silhouette, color, prints, material, features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  if (style === "flagship") {
    return [
      FIDELITY_BLOCK,
      PRINTED_DESIGN_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE premium e-commerce flagship product listing — a clean, modern marketplace top-tier composition.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print, graphic, embroidery, color, button, seam, hardware stays exactly as in the source). The LAYOUT around the product is graphic and aggressive. You ARE permitted (and required) to do all of the following — these are SCENE / COMPOSITION operations, not product modifications:",
      "- Build a vertical split background underneath the product.",
      "- Re-light, re-pose, and re-crop the product to fit the new layout.",
      "- Replace the original photo's environment entirely.",
      "- Add typography, feature cards, watermark, and CTA pill in negative space.",
      "",
      "STYLE — FLAGSHIP LISTING:",
      "",
      "COLOR LOCK — zero decision freedom:",
      "Identify the product's dominant color in the reference (one word — red,",
      "blue, green, etc.). The accent color used for the right-region",
      "background, the CTA pill, and any tech-tag pills MUST EQUAL that exact",
      "color (same hue, same saturation). A red product → red accent. A blue",
      "product → blue accent. Edge case: if the product is black, white, or a",
      "near-neutral gray, pick a single rich saturated hue (cobalt, emerald,",
      "crimson, amber). The product's own colors stay bit-identical to the",
      "reference — never recolor the product to match the accent.",
      "",
      "Background:",
      "- Vertical asymmetric split. The LEFT ~40% of the canvas is pure white;",
      "  the RIGHT ~60% is the accent color from the COLOR LOCK above. The two",
      "  regions meet at a clean vertical edge running floor to ceiling.",
      "",
      "Product placement — the product appears in EXACTLY these two places and",
      "nowhere else on the canvas:",
      "1. HERO CROP in the colored region: a portion of the product enlarged",
      "   to fill the right ~60% of the canvas, bleeding off the right and",
      "   bottom edges by design. Re-light cleanly. Whatever portion is",
      "   visible must match the reference's prints, color, and material",
      "   exactly. Occupies ~70–85% of the colored region.",
      "2. FEATURE CARD THUMBNAILS: small product thumbnails tucked in the",
      "   corner of each feature card panel in the white region.",
      "The white region OUTSIDE the feature cards is solid white. The colored",
      "region OUTSIDE the hero crop is solid accent color. No faded copies, no",
      "third appearances, no product crossing the seam, no original photo's",
      "environment leaking through anywhere.",
      "",
      "White region (left) contents, top to bottom:",
      "- Top nav strip: a small brand wordmark on the far left (only if the",
      "  description provides a brand name; otherwise omit), 3–4 short tab",
      "  labels authored from product attributes, optional small line icons",
      "  (heart + cart) on the far right.",
      "- Headline block: a bold sans CATEGORY word, the larger product /",
      "  model NAME beneath, a one-line POSITIONING statement under that. All",
      "  in dark near-black with generous breathing room between tiers.",
      "- Feature card stack: 2–3 rounded-corner light-gray panels stacked",
      "  vertically. Each panel contains a small pill-shaped tech / spec tag",
      "  (1–2 words drawn from the description) in the accent color, a 1–2",
      "  line caption beneath, and a small thumbnail of the reference photo",
      "  in the corner.",
      "- Bottom CTA: a large rounded pill in the accent color with white text",
      "  in two tiers — a small label on top (a primary spec name from the",
      "  description) and an oversized bold value beneath (the corresponding",
      "  spec value, in tabular figures).",
      "",
      "Colored region (right) contents:",
      "- The hero crop only.",
      "- Optional vertical script or italic of the product name running up",
      "  the right edge of the colored region at very low opacity, decorative",
      "  texture only. Skip entirely if no product name is in the description.",
      "",
      "Typography: ONE clean modern sans-serif family throughout (Inter / SF",
      "Pro / Söhne feel). Headlines in dark near-black; CTA value text in",
      "white. Tabular figures for any numeric value. No serif and no script",
      "except for the optional vertical watermark.",
      "",
      "Avoid: gradients, atmospheric haze, vignettes, full-uncropped product",
      "hero shots (the dramatic crop is essential), color blocking beyond the",
      "white-plus-one-accent split, '+' callout chips, numbered features",
      "(01/02/03), fabricated price tags, fabricated star counts, decorative",
      "botanical props, oversized backdrop typography. This style is",
      "informational, refined, and reads as a flagship product listing — not",
      "a brand poster.",
      "",
      "Reference: Apple product pages, Nike flagship product listings,",
      "Allbirds product imagery, premium D2C e-commerce hero pages.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The split-canvas listing layout is YOUR creative work. The product",
      "itself is NOT. The product appears in exactly two places (hero crop +",
      "feature-card thumbnails) and nowhere else — never as a faded backdrop,",
      "never crossing the seam, never in the white region's empty space. The",
      "product's silhouette, color, material, every printed text, every",
      "graphic illustration, every embroidered character, every pattern,",
      "every button, seam, label, hem, and hardware element is FIXED — copied",
      "from the reference, never re-imagined. Run the 5-point identity check",
      "from the ENHANCEMENT block one final time before committing pixels:",
      "silhouette, color, prints, material, features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }


  if (style === "luxury") {
    return [
      FIDELITY_BLOCK,
      PRINTED_DESIGN_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE LUXURY EDITORIAL composition — a single dramatic dark-cinematic image in the style of premium fragrance, whisky, watch, and leather-goods campaigns.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print,",
      "graphic, embroidery, color, button, seam, hardware stays exactly as in the",
      "source). The composition AROUND the product is fully designed in the",
      "luxury-editorial idiom. You ARE permitted (and required) to do all of the",
      "following — these are SCENE / COMPOSITION operations, not product",
      "modifications:",
      "- Replace the original background entirely with a deep cinematic backdrop.",
      "- Re-light the product with a dramatic single-key setup: a crisp rim",
      "  light from behind separating the silhouette from the dark backdrop, a",
      "  soft key from upper-left modulating the front, deep falloff into",
      "  shadow on the opposite side, controlled specular highlights.",
      "- Add a heavy edge vignette pulling the eye toward center.",
      "- Add subtle volumetric atmosphere — fine dust catching the rim light,",
      "  soft drifting haze for depth.",
      "- Compose all typography in a single warm metallic accent.",
      "",
      "STYLE — LUXURY EDITORIAL (premium fragrance / whisky / watch / leather-goods campaign):",
      "- Background: a single very dark, slightly textured tone — deep",
      "  charcoal, near-black, oxblood, midnight blue, deep forest green, or a",
      "  very deep version of the product's own dominant hue. NEVER pure flat",
      "  black; the backdrop has a subtle gradient falloff and fine grain, like",
      "  a real photographic studio backdrop. A heavy edge vignette pulls",
      "  inward.",
      "- Product: spotlit and centered (or slightly off-center on a rule-of-",
      "  thirds anchor), occupying ~50–65% of canvas height. A crisp white rim",
      "  light from behind defines the silhouette against the dark backdrop.",
      "  A soft key light from upper-left modulates the front. Deep falloff",
      "  into shadow on the opposite side gives the product real volume.",
      "  Specular highlights on glass, metal, leather, polished plastic show",
      "  clear shape — never airbrushed blobs. A believable contact shadow",
      "  grounds the product on its surface.",
      "- Atmosphere: subtle volumetric haze drifting through the scene; fine",
      "  dust particles catching the rim light; a soft bloom around the",
      "  brightest highlights. Hushed, slow, expensive mood — never overlit,",
      "  never theatrical, never cheerful.",
      "- Color discipline: the product's natural colors come through bit-",
      "  identically (same red is the same red, same blue is the same blue —",
      "  the dark scene re-lights the product but never recolors it). The",
      "  background is one single very dark hue. ONE warm metallic accent —",
      "  gold, champagne, copper, brass, or amber — is the only color used",
      "  for typography and any thin rules. Body text in a slightly",
      "  desaturated near-white. NO third color, NO neon, NO pastel, NO",
      "  bright accent.",
      "- Typography — a single hero headline; clutter is the enemy:",
      "    1. ONE oversized headline in a HIGH-CONTRAST DIDONE display serif",
      "       (Bodoni, Didot, Vogue-masthead feel) OR a tall condensed sans",
      "       for tech-leaning products. Set in the metallic accent. 2–4",
      "       words drawn from the description (product name or short",
      "       evocative phrase). Generous letter-spacing, tight optical",
      "       kerning at display size.",
      "    2. A small italic or light-weight sans subtitle beneath the",
      "       headline in slightly desaturated near-white, 4–8 words max —",
      "       only if the description supports it; otherwise omit entirely.",
      "    3. A thin hairline rule in the metallic accent separates the",
      "       headline from the subtitle.",
      "    4. Optionally a small all-caps category word above the headline",
      "       at very small size in the metallic accent (e.g. one short",
      "       word from the description's category).",
      "- Composition: the headline sits in deliberate negative space — top",
      "  center, beside the product, or floating in the dark. Never crowding",
      "  the product, never overlapping its silhouette. The product occupies",
      "  the visual center; type frames the silence around it.",
      "- Avoid: bright pastel backgrounds, atmospheric airy haze, glassy '+'",
      "  chips, circular icon badges, pill callouts, multi-panel grids, color",
      "  blocking, bullet feature lists, numbered features (01/02/03), CTA",
      "  buttons, fake price tags, decorative botanical props, busy",
      "  backgrounds, photography that feels overlit or cheerful. This style",
      "  is hushed, atmospheric, and reverent — every element is restrained.",
      "",
      "Reference: Tom Ford fragrance ads, Chanel No. 5 print imagery, Dior",
      "J'adore campaigns, premium whisky (The Macallan, Hennessy) hero ads,",
      "luxury watch (Rolex, Omega) campaigns, Acqua di Parma, Le Labo",
      "cinematic. Imagine this as a single full-page luxury campaign",
      "photograph in a glossy print magazine.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The luxury-editorial scene is YOUR creative work. The product itself",
      "is NOT. Apply the two-photographers metaphor: the product in the",
      "output is the SAME PHYSICAL ITEM as the reference, photographed by a",
      "luxury-campaign photographer in a studio with dramatic lighting. The",
      "dark backdrop, vignette, atmospheric haze, dramatic lighting,",
      "metallic typography, and composition are yours to author. The",
      "product's silhouette, color, material, every printed text, every",
      "graphic illustration, every embroidered character, every pattern,",
      "every button, seam, label, hem, and hardware element is FIXED —",
      "copied from the reference, never re-imagined. Run the 5-point",
      "identity check from the ENHANCEMENT block one final time before",
      "committing pixels: silhouette, color, prints, material, features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  if (style === "vivid") {
    return [
      FIDELITY_BLOCK,
      PRINTED_DESIGN_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE BOLD VIVID composition — a single saturated, scroll-stopping product hero in the style of contemporary social-commerce billboards.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print,",
      "graphic, embroidery, color, button, seam, hardware stays exactly as in the",
      "source). The composition AROUND the product is loud, saturated, and",
      "graphic. You ARE permitted (and required) to do all of the following —",
      "these are SCENE / COMPOSITION operations, not product modifications:",
      "- Replace the original background entirely with one fully saturated color.",
      "- Re-light the product cleanly so it pops forward against the bg.",
      "- Add ONE energy device (motion, graphic shapes, or speed lines).",
      "- Add a confident headline and at most one small badge.",
      "",
      "STYLE — BOLD VIVID (high-energy hero, scroll-stopping social-commerce / billboard):",
      "- Background: ONE bold, fully saturated color — electric orange, hot",
      "  pink, cobalt blue, lime green, cyber yellow, electric coral, deep",
      "  red, or any single richly saturated hue. Pick whichever harmonizes",
      "  with the product without competing. Flat, OR with a single subtle",
      "  large radial highlight behind the product. NEVER pastel, NEVER",
      "  desaturated, NEVER a multi-hue gradient.",
      "- Color discipline: monochromatic in one tonal range — backdrop, any",
      "  accent shape, and any callout backing are all variations of the",
      "  same hue (lighter / darker / shifted). White is allowed only for",
      "  crisp text or small UI marks. The product's natural colors come",
      "  through unchanged. NO multi-color icon palette, NO rainbow accents.",
      "- Product: HERO, photoreal, sharply lit, occupying ~45–60% of canvas",
      "  height. Confident composition — centered upright, tilted for motion,",
      "  slightly cropped, or paired with a second smaller angle. Soft",
      "  believable contact shadow on the saturated surface.",
      "- Energy device — pick ONE that fits the product, never combine:",
      "    (a) ABSTRACT MOTION: a liquid splash, smoke ribbon, particle",
      "        burst, swirl of powder, scattered petals or beans frozen mid-",
      "        air around the product (only if natural for the product).",
      "    (b) GRAPHIC MOTION: chunky tilted geometric shapes (filled",
      "        circles, arcs, pills, soft blobs, halftone dot field, scattered",
      "        confetti) behind or around the product, tinted to the scene.",
      "    (c) SPEED LINES: bold tilted parallel stripes or a sunburst",
      "        radiating from behind the product, in a slightly darker shade",
      "        of the scene.",
      "- Typography: ONE confident oversized display sans-serif headline",
      "  (bold or black weight, ALL CAPS or tall proper case). Set in white",
      "  OR a much darker shade of the scene color — pick whichever holds",
      "  strongest contrast. Optional thin stroke or subtle drop-color shadow",
      "  for punch. Smaller secondary labels in a clean medium-weight sans.",
      "- Callouts: pick ONE consistent treatment and use throughout —",
      "    (i) short bold proper-case or all-caps plain text with NO",
      "        containers, OR",
      "    (ii) compact rectangular color-block badges in white or the",
      "         darker scene shade, holding 1–3 words.",
      "  Place anchored near the relevant detail, not floating arbitrarily.",
      "  NEVER combine treatments.",
      "- Mood: loud, confident, energetic, scroll-stopping. The image should",
      "  pop off a feed at thumbnail size.",
      "- Avoid: multi-hue gradients, atmospheric haze, vignettes, soft",
      "  pastels, glassy '+' pill chips, thin-line icons, leader lines,",
      "  dimension lines, magazine serifs, cinematic dark backgrounds,",
      "  lifestyle scenes, fake CTA buttons, fake phone numbers. This style",
      "  lives or dies on saturation, contrast, and ONE energy device.",
      "",
      "Reference: contemporary D2C ad creative, Glossier campaign visuals,",
      "Mailchimp visual identity, Spotify Wrapped imagery, scroll-stopping",
      "social-commerce hero shots.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The vivid scene is YOUR creative work. The product itself is NOT.",
      "Apply the two-photographers metaphor: the product in the output is",
      "the SAME PHYSICAL ITEM as the reference, photographed against a",
      "saturated backdrop. The saturated background, the energy device,",
      "the typography, and the callouts are yours to author. The product's",
      "silhouette, color, material, every printed text, every graphic",
      "illustration, every embroidered character, every pattern, every",
      "button, seam, label, hem, and hardware element is FIXED — copied",
      "from the reference, never re-imagined. Run the 5-point identity",
      "check from the ENHANCEMENT block one final time before committing",
      "pixels: silhouette, color, prints, material, features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  if (style === "lifestyle") {
    return [
      FIDELITY_BLOCK,
      PRINTED_DESIGN_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE LIFESTYLE HERO composition — a single magazine-quality scene of the product staged in a believable real-world environment.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print,",
      "graphic, embroidery, color, button, seam, hardware stays exactly as in the",
      "source). The environment AROUND the product is fully designed in a",
      "magazine-editorial style. You ARE permitted (and required) to do all of",
      "the following — these are SCENE / COMPOSITION operations, not product",
      "modifications:",
      "- Replace the original background entirely with a contextual real-world",
      "  environment chosen to fit the product's category (see SCENE PICKER).",
      "- Re-light the product to match the new scene's natural light direction.",
      "- Add believable contextual props (one or two only — never crowding).",
      "- Add elegant magazine-style typography in negative space.",
      "",
      "STYLE — LIFESTYLE HERO (Kinfolk / Cereal magazine editorial / Aesop interiors):",
      "- SCENE PICKER — pick ONE environment that fits the product's category:",
      "    • Skincare / cosmetics → marble bathroom shelf, soft linen, pale",
      "      tile, sheer curtain catching morning light.",
      "    • Kitchen / food / cookware → wooden farmhouse table or marble",
      "      counter, a few fresh ingredients, soft window light.",
      "    • Apparel / textile → sunlit bedroom, linen bedding, pale wood",
      "      floor, a folded blanket nearby.",
      "    • Tech / gadget → modern desk, pale concrete or oak surface, a",
      "      single indoor plant out of focus, daylight from a side window.",
      "    • Bath / shower / plumbing → marble bathroom alcove, pale tile,",
      "      gentle steam haze, soft daylight from above.",
      "    • Outdoor / camping / sport → outdoor wooden surface, soft natural",
      "      light, a hint of greenery or stone in the background.",
      "    • Beauty / fragrance → travertine or wood vanity, sheer fabric,",
      "      dried botanicals, golden-hour window light.",
      "    • Home / decor → linen sofa or wood shelf, neutral wall, soft",
      "      daylight, a stack of books or single ceramic piece nearby.",
      "  If the product doesn't match a category, pick a bright minimalist",
      "  interior with pale wood + linen + soft daylight as the safe default.",
      "- Lighting: SOFT NATURAL DAYLIGHT pouring from a single window upper-",
      "  left, warm gentle fill, gentle shadows. Bright, airy, slow. NOT",
      "  studio strobe, NOT cinematic spotlight, NOT dark moody.",
      "- Composition: the product is staged where it would naturally sit in",
      "  this environment — not floating. Believable contact and scale. Off-",
      "  center on a rule-of-thirds anchor, occupying ~30–45% of canvas",
      "  height (less than other styles — the scene matters here too).",
      "  Shallow depth of field; background softens into creamy bokeh.",
      "- Contextual props: one or two only, contextually believable (a folded",
      "  cloth, a coffee cup, a sprig of herb, a stack of books, a single",
      "  ceramic). Never crowding, never stealing attention from the product.",
      "- Color: warm and tactile, drawn from natural materials (cream linen,",
      "  pale wood, travertine, marble, sage green, stone gray, soft beige).",
      "  The product's natural colors come through unchanged.",
      "- Typography — magazine-style:",
      "    1. ONE elegant serif headline (Garamond / Caslon / Cormorant feel)",
      "       in a soft dark tone (charcoal, deep brown), 2–4 words drawn",
      "       from the description, placed in negative space.",
      "    2. A small all-caps category word above the headline in a clean",
      "       light sans, very small, with light tracking.",
      "    3. Optional one-line caption in a clean light-weight sans beneath",
      "       the headline.",
      "- Callouts: minimal — small thin underlined labels with short captions",
      "  tucked into corners like a magazine spread. NO chips, NO badges, NO",
      "  bubbles, NO leader lines.",
      "- Mood: warm, slow, tactile, lived-in. The image should feel like a",
      "  page from Kinfolk or Cereal — not a marketplace ad.",
      "- Avoid: clinical product-shot lighting, flat studio backgrounds,",
      "  color blocking, cinematic dark vignettes, atmospheric haze, glassy",
      "  '+' pill chips, circular icon badges, multi-panel grids, bold",
      "  display sans headlines, fake CTA buttons. This style is quiet,",
      "  magazine-grade, and human.",
      "",
      "Reference: Kinfolk magazine spreads, Cereal magazine product",
      "photography, Aesop interior campaigns, Goop product features, Toast",
      "lifestyle imagery. Imagine this as a single full-page magazine still",
      "life shot in soft natural daylight.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The lifestyle scene is YOUR creative work. The product itself is NOT.",
      "Apply the two-photographers metaphor: the product in the output is",
      "the SAME PHYSICAL ITEM as the reference, staged in a real environment",
      "by a magazine photographer. The environment, the props, the natural",
      "light, the magazine typography, and the composition are yours to",
      "author. The product's silhouette, color, material, every printed",
      "text, every graphic illustration, every embroidered character, every",
      "pattern, every button, seam, label, hem, and hardware element is",
      "FIXED — copied from the reference, never re-imagined. Run the 5-",
      "point identity check from the ENHANCEMENT block one final time",
      "before committing pixels: silhouette, color, prints, material,",
      "features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  if (style === "wellness") {
    return [
      FIDELITY_BLOCK,
      PRINTED_DESIGN_BLOCK,
      COMPOSITING_DIRECTIVE,
      ENHANCEMENT_BLOCK,
      copyDirective,
      "",
      "Edit the attached product photo into ONE WELLNESS APOTHECARY composition — a single warm, ornamental, abundant image in the style of premium skincare, cosmetics, and supplement campaigns.",
      "",
      "WHAT 'EDIT' MEANS HERE — read carefully:",
      "Keep the product itself bit-identical to the reference photo (every print,",
      "graphic, embroidery, color, button, seam, hardware stays exactly as in the",
      "source). The composition AROUND the product is warm, ornamental, and",
      "abundant. You ARE permitted (and required) to do all of the following —",
      "these are SCENE / COMPOSITION operations, not product modifications:",
      "- Replace the original background entirely with a warm monochromatic",
      "  gradient drawn from the product's tone.",
      "- Re-light the product backlit by a soft radial glow.",
      "- Add a stone or wood plinth beneath the product.",
      "- Add believable botanical / ingredient props at the base.",
      "- Add a sculptural splash of the product's liquid behind it.",
      "- Add ornamental leaf silhouettes in the upper corners.",
      "- Add a two-part centered headline + small icon callouts + footer.",
      "",
      "STYLE — WELLNESS APOTHECARY (premium skincare / cosmetics / supplement campaign):",
      "- Background: warm monochromatic gradient drawn from the product's",
      "  dominant tone, pushed toward an abundant luxe color (amber-honey",
      "  for amber products, jade-emerald for green, blush-rose for pink,",
      "  pearl-champagne for white, deep ivory for cream). A SOFT RADIAL",
      "  HIGHLIGHT glows from behind the product so it reads luminous.",
      "  Decorative semi-transparent botanical silhouettes (palm fronds,",
      "  leaves, branches) in the same tonal family fade into the upper",
      "  corners as ornamentation.",
      "- Composition: product centered on a textured natural-stone slab,",
      "  rough sandstone, or warm wood podium. Behind the product, a",
      "  sculptural curving splash of the product's liquid (oil, serum,",
      "  cream, water) frozen mid-motion as a hero decorative element. At",
      "  the base, a small cluster of the product's key ingredient (nuts,",
      "  seeds, petals, fruit, herbs) tinted to harmonize with the scene.",
      "- Product: occupies ~40–50% of canvas height, centered, backlit by",
      "  the radial glow so any glass or plastic reads luminous. Believable",
      "  contact shadow on the stone or wood surface. The product's natural",
      "  colors come through unchanged.",
      "- Typography — centered, two-part hero headline:",
      "    1. The first word in a clean serif (Garamond / Cormorant feel)",
      "       in white or near-white.",
      "    2. The second word in a flowing italic script in a deeper shade",
      "       of the scene color, the script overlapping the serif slightly.",
      "    3. A small brand mark or maker word in the upper-left corner",
      "       — only if the description provides a brand name; otherwise",
      "       omit. Do NOT invent a brand name.",
      "- Feature callouts: four small pale circular badges arranged 2-up on",
      "  the LEFT and 2-up on the RIGHT, flanking the product. Each badge",
      "  contains a thin-line monochrome icon (drop, leaf, sun, certificate,",
      "  etc.) sitting ON the badge with no '+' marks, and a short bold two-",
      "  line label beneath it.",
      "- Color: warm monochromatic family in one luxe tone (gold / amber /",
      "  honey, jade / emerald, blush / rose, pearl / champagne, deep ivory)",
      "  with a white serif headline accent. NO multi-color icons, NO",
      "  foreign colors except the brand mark.",
      "- Lighting: warm, abundant, glowing. The radial highlight behind the",
      "  product is the visual hero — everything reads as bathed in golden",
      "  warm light.",
      "- Mood: ornamental, abundant, generous, premium-natural. The image",
      "  should feel like a page from a high-end skincare brochure.",
      "- Avoid: cool clinical lighting, flat neutral backgrounds, glassy",
      "  '+' pill chips, dark cinematic vignettes, multi-panel grids,",
      "  condensed display sans headlines, color blocking, sharp graphic",
      "  geometry, fabricated phone numbers, fabricated website URLs,",
      "  fabricated email addresses, fabricated social-media handles, any",
      "  invented contact details, any footer or strap-line containing",
      "  contact-style text. This style is warm, ornamental, and abundant",
      "  — every element supports a feeling of luxury-natural plenty.",
      "",
      "Reference: Aesop skincare campaigns, Le Labo product brochures,",
      "Drunk Elephant editorial spreads, Augustinus Bader visuals, premium",
      "supplement and apothecary brand campaigns. Imagine this as a single",
      "full-page advertisement in a wellness magazine.",
      "",
      "Render the product faithfully from the attached reference photos —",
      "accurate color, shape, branding, proportions. Do not invent product details.",
      "",
      "CRITICAL — Language rule:",
      languageRule,
      "",
      "Hard rules:",
      "- Output exactly ONE image.",
      "- No watermarks, no fake logos, no fabricated brand names.",
      "- All text spelled correctly.",
      "",
      "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
      "The wellness-apothecary scene is YOUR creative work. The product",
      "itself is NOT. Apply the two-photographers metaphor: the product in",
      "the output is the SAME PHYSICAL ITEM as the reference, photographed",
      "in a warm premium skincare campaign. The warm gradient, radial glow,",
      "splash, ingredient cluster, botanical silhouettes, stone plinth, two-",
      "part typography, icon badges, and footer are yours to author. The",
      "product's silhouette, color, material, every printed text, every",
      "graphic illustration, every embroidered character, every pattern,",
      "every button, seam, label, hem, and hardware element is FIXED —",
      "copied from the reference, never re-imagined. Run the 5-point",
      "identity check from the ENHANCEMENT block one final time before",
      "committing pixels: silhouette, color, prints, material, features.",
      "",
      "Product description:",
      '"""',
      trimmed,
      '"""',
    ].join("\n");
  }

  // default: glass
  return [
    FIDELITY_BLOCK,
    PRINTED_DESIGN_BLOCK,
    COMPOSITING_DIRECTIVE,
    ENHANCEMENT_BLOCK,
    copyDirective,
    "",
    "STEP 1 — DECORATION AUDIT (do this BEFORE composing the scene):",
    "Look at every reference photo. List, in your head, every single printed",
    "word, every graphic illustration, every embroidered character, every",
    "pattern motif visible on the product. If the t-shirt says 'MY FRIEND'",
    "with a cartoon character, the t-shirt in the output MUST say 'MY FRIEND'",
    "with the SAME cartoon character in the SAME pose, color, and position.",
    "If the bottle label has specific text and a specific image, that exact",
    "text and that exact image MUST appear on the bottle in the output.",
    "These printed and embroidered elements are the HERO of the entire image.",
    "Build the glassmorphism scene AROUND them — never let the scene replace,",
    "simplify, restyle, or omit them. If you cannot reproduce a printed",
    "graphic exactly, leave that area blank rather than inventing a new one.",
    "",
    "STEP 2 — SCENE PROTECTS THE PRODUCT:",
    "Atmospheric haze, bloom, glass bubbles, glass shelves, frosted panels,",
    "and any other scene element must NEVER blur, soften, fade, occlude, or",
    "pass in front of the product itself or any printed/embroidered content",
    "on it. The product is photographically crisp from edge to edge, with",
    "every graphic clearly legible. The glass effects belong to the SCENE",
    "AROUND the product, not the product surface.",
    "",
    "Now edit the attached product photo into ONE editorial advertisement in",
    "glassmorphism style. The product itself stays unchanged; only the scene,",
    "atmosphere, glass staging elements, and typography are added around it.",
    "The ENTIRE composition must feel layered with glass — not just the callouts.",
    "",
    "Setting — choose CONTEXTUALLY based on the product, build either:",
    "(a) A bright interior suited to the product's lifestyle context, OR",
    "(b) A styled commercial scene with THEMED props on a complementary",
    "    backdrop that reinforces the product's identity:",
    "    - Sea / ocean / fresh → sand, seashells, coral, soft teal backdrop.",
    "    - Garden / floral / botanical → leaves, petals, soft green backdrop.",
    "    - Citrus / tropical → fruit slices, palm leaves, warm yellow backdrop.",
    "    - Winter / mint / cool → frost, eucalyptus, pale blue backdrop.",
    "    - Forest / woody / spice → bark, dried botanicals, warm brown backdrop.",
    "    - Beauty / skincare → soft drapery, marble, pearl tones.",
    "    - Apparel → sunlit bedroom, linen, pale wood floor.",
    "    - Tech → modern desk, pale concrete or oak.",
    "    - Kitchen / food → wooden table, marble counter, fresh ingredients.",
    "    - Bath / shower / plumbing → marble bathroom, pale tile, soft daylight.",
    "    - Toys / kids → pastel nursery, soft playful props.",
    "",
    "If no theme is obvious, choose a bright interior that fits. The setting",
    "must always be bright with atmospheric depth. Vary specific props per",
    "product so different products do NOT share the same backdrop.",
    "",
    "Glassmorphism scene staging — the COMPOSITION must feel glass-layered:",
    "- The product is staged WITH at least one large translucent or frosted",
    "  glass element in the scene, chosen to fit the product type:",
    "    • Tabletop / standing products (bottles, jars, gadgets) → a clear",
    "      glass shelf or pedestal beneath the product PLUS a tall translucent",
    "      glass panel positioned behind it as a vertical backdrop layer.",
    "    • Wall-mounted products (shower, faucets, sconces) → a tall frosted",
    "      glass shower screen, glass partition, or translucent glass panel",
    "      visible alongside the product as an architectural element.",
    "   • Apparel / textile → present the garment FULLY UNFOLDED and FLAT-LAID",
    "      on a clear glass tray or acrylic platter, front facing the camera,",
    "      so every printed graphic, embroidered detail, text, and pattern is",
    "      visible from collar to hem at FULL SIZE and SHARP focus. The",
    "      printed/embroidered area on the garment is the focal point of the",
    "      whole frame — render it photographically, not as a stylized",
    "      reinterpretation. Reproduce every word, every character, every",
    "      illustration exactly as in the references. Do NOT fold, stack,",
    "      crumple, or partially obscure the garment. If the set has multiple",
    "      pieces (top + bottom), lay them side by side — both fully visible,",
    "      both fronts facing up. A soft frosted glass panel behind for depth,",
    "      sitting strictly behind the garment with no overlap onto its print.",
    "    • Footwear → a low glass platform beneath plus a vertical frosted",
    "      glass panel behind for depth.",
    "- These glass staging elements must have real glass physics: subtle",
    "  refraction of the background through them, defined edges, soft",
    "  highlights along the upper rim, gentle inner reflections.",
    "- Glass staging elements (shelves, panels, trays, partitions) sit BEHIND",
    "  or BESIDE the product. They must NEVER cover, overlap, or pass in",
    "  front of any printed text, embroidered character, graphic illustration,",
    "  or pattern that appears on the product itself. Every decoration on the",
    "  product remains fully visible and unobstructed.",
    "- A subtle atmospheric haze and gentle bloom around bright areas",
    "  reinforce the soft, layered, glass-like feel of the whole scene.",
    "- Together with the bubble callouts, this staging creates layered",
    "  glassmorphism across the entire image — never just on the callouts.",
    "",
    "Composition — the PRODUCT is the unquestionable hero:",
    "- Large and dominant, occupying 55–65% of frame height, fully in frame.",
    "- Centered or slightly off-center, three-quarter angle, slightly tilted.",
    "- Photoreal magazine quality. Use enough depth of field that the ENTIRE",
    "  product — and every printed text, graphic, embroidery, and pattern on",
    "  it — stays in sharp focus. Background scene may be softened, but never",
    "  the product itself.",
    "",
    "Typography — ONE single headline only. NO subtitle, NO tagline:",
    "- HEADLINE: SHORT product name, 2–3 words MAX (prefer 2). Distill from",
    "  the description; never paste the full SKU. Set in a beautiful editorial",
    "  serif with subtle weight variation between words, generous letter-",
    "  spacing, in a near-black or deep tone that reads cleanly against the",
    "  scene. Placed in prominent negative space beside the product.",
    "- DO NOT add any tagline, subtitle, descriptor line, product type label,",
    "  size/volume label, or secondary text beneath the headline. The headline",
    "  stands alone. All product attributes belong inside the glass bubbles.",
    "- CRITICAL: the headline appears ONCE and ONLY ONCE in the entire image.",
    "  NEVER duplicate it, NEVER render it twice in different colors.",
    "- The headline sits DIRECTLY on the background. It is NOT contained in",
    "  any frosted glass card or panel.",
    "",
    "Glass bubble callouts — supporting glassmorphism element:",
    "- Exactly 2–3 small frosted glass BUBBLES (rounded blob, teardrop, or",
    "  oval shapes — NOT rectangular cards) float asymmetrically around the",
    "  product.",
    "- Each bubble must read as REAL TRANSPARENT GLASS:",
    "    • Visibly transparent center showing the blurred refracted background.",
    "    • A sharp curved highlight along the upper edge.",
    "    • A softer secondary highlight along the lower-left edge.",
    "    • A thin, clearly-defined outer rim — the bubble must have a visible",
    "      glass edge, not fade into the background.",
    "    • A soft drop shadow with a small sliver of light beneath.",
    "- Bubble highlights must be SOFT, ROUND specular catches like real light",
    "  on glass. DO NOT render star-shaped sparkles, four-pointed sparkle",
    "  crosses, lens flares, twinkle effects, or fairy-magic glow. This is",
    "  editorial product photography, not Y2K graphics.",
    "- Each bubble contains a small '+' marker followed by ONE short attribute",
    "  in 1–3 words (e.g. '100% Cotton', 'Long Lasting', 'Matte Finish').",
    "  Text is crisp and unblurred, set in a clean modern sans-serif, dark gray.",
    "- Distribute bubbles asymmetrically — never symmetric corners. Vary",
    "  their sizes slightly. Keep them small and supporting; they must not",
    "  compete with the product.",
    "- Bubbles are placed in the negative space AROUND the product. They",
    "  must NEVER overlap the product, sit in front of any printed graphic,",
    "  text, or embroidered element on the product, or cast their drop",
    "  shadow onto the printed area. Maintain a clear gap between every",
    "  bubble and the product silhouette.",
    "",
    "Palette: bright and airy, with one dominant accent hue drawn from the",
    "product or its theme. Tonally unified across scene, type, and bubbles.",
    "",
    "Render the product faithfully from the attached reference photos —",
    "accurate color, shape, branding, proportions, fully and prominently shown.",
    "Every printed text, embroidered character, graphic illustration, and",
    "pattern visible on the product in the references MUST be reproduced",
    "exactly: character-for-character, color-for-color, position-for-position.",
    "If you cannot reproduce a graphic faithfully, leave it blank rather than",
    "substituting a different one. Do not invent product details.",
    "",
    "CRITICAL — Language rule:",
    languageRule,
    "",
    "Style references: premium consumer-goods advertising, modern lifestyle",
    "brand campaigns with layered glass staging, editorial product posters.",
    "",
    "Output exactly ONE image. No watermarks, no fake logos, all text spelled",
    "correctly.",
    "",
    "FINAL CHECK BEFORE RENDERING — re-read this and apply it:",
    "The glassmorphism scene is YOUR creative work. The product itself is",
    "NOT. Apply the two-photographers metaphor: the product in the output is",
    "the SAME PHYSICAL ITEM as the reference, photographed by a professional",
    "in better conditions. The atmospheric scene, glass staging, bubbles,",
    "props, palette, and lighting are yours to compose. The product's",
    "silhouette, color, material, every printed text, every graphic",
    "illustration, every embroidered character, every pattern, every button,",
    "seam, label, hem, and hardware element is FIXED — copied from the",
    "reference, never re-imagined. Run the 5-point identity check from the",
    "ENHANCEMENT block one final time before committing pixels: silhouette,",
    "color, prints, material, features. If any drift, restore the reference's",
    "identity first.",
    "",
    "Product description:",
    '"""',
    trimmed,
    '"""',
  ].join("\n");
}

export async function generateInfographic({
  images,
  description,
  aspectRatio = "3:4",
  style = "glass",
  language = "en",
}: InfographicInput): Promise<EditResult> {
  if (images.length === 0) {
    throw new Error("At least one product image is required.");
  }
  if (images.length > 4) {
    throw new Error("Up to 4 product images are supported.");
  }

  const parts: Part[] = images.map((img) => ({
    inlineData: { mimeType: img.mimeType, data: img.base64 },
  }));
  parts.push({ text: buildInfographicPrompt(description, style, language) });

  const response = await ai.models.generateContent({
    model: INFOGRAPHIC_MODEL,
    contents: [{ role: "user", parts }],
    config: {
      responseModalities: ["IMAGE"],
      imageConfig: { aspectRatio, imageSize: "2K" },
    },
  });

  return extractImage(response);
}
